# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_patient_registration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
from Main_screen import *

class Ui_NP_Registration(QWidget):
    def setupUi(self, NPRegistration):
        NPRegistration.setObjectName("NPRegistration")
        NPRegistration.resize(1100, 800)
        NPRegistration.setMinimumSize(QtCore.QSize(1100, 800))
        NPRegistration.setMaximumSize(QtCore.QSize(1100, 800))
        self.centralwidget = QtWidgets.QWidget(NPRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.newPatientLabel = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel.setGeometry(QtCore.QRect(240, 70, 621, 61))
        self.newPatientLabel.setObjectName("newPatientLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(241, 175, 51, 31))
        self.label.setObjectName("label")
        self.NP_name_first = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_first.setGeometry(QtCore.QRect(296, 181, 161, 22))
        self.NP_name_first.setObjectName("NP_name_first")
        self.NP_name_MI = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_MI.setGeometry(QtCore.QRect(460, 181, 20, 22))
        self.NP_name_MI.setObjectName("NP_name_MI")
        self.NP_name_last = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_last.setGeometry(QtCore.QRect(483, 181, 161, 22))
        self.NP_name_last.setObjectName("NP_name_last")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(296, 161, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(461, 160, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(486, 160, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(651, 175, 51, 31))
        self.label_5.setObjectName("label_5")
        self.NP_DOB = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_DOB.setGeometry(QtCore.QRect(697, 180, 161, 22))
        self.NP_DOB.setObjectName("NP_DOB")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(241, 211, 51, 31))
        self.label_6.setObjectName("label_6")
        self.NP_sex_M = QtWidgets.QRadioButton(self.centralwidget)
        self.NP_sex_M.setGeometry(QtCore.QRect(289, 216, 51, 20))
        self.NP_sex_M.setObjectName("NP_sex_M")
        self.NP_sex_F = QtWidgets.QRadioButton(self.centralwidget)
        self.NP_sex_F.setGeometry(QtCore.QRect(342, 217, 51, 20))
        self.NP_sex_F.setObjectName("NP_sex_F")
        self.NP_address = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_address.setGeometry(QtCore.QRect(487, 217, 371, 22))
        self.NP_address.setObjectName("NP_address")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(414, 211, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(239, 245, 81, 31))
        self.label_8.setObjectName("label_8")
        self.NP_city = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_city.setGeometry(QtCore.QRect(330, 251, 161, 22))
        self.NP_city.setObjectName("NP_city")
        self.NP_state = QtWidgets.QComboBox(self.centralwidget)
        self.NP_state.setGeometry(QtCore.QRect(500, 251, 51, 22))
        self.NP_state.setObjectName("NP_state")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_zip = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_zip.setGeometry(QtCore.QRect(697, 251, 161, 22))
        self.NP_zip.setObjectName("NP_zip")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(653, 246, 51, 31))
        self.label_9.setObjectName("label_9")
        self.NP_prim_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_prim_phone.setGeometry(QtCore.QRect(360, 286, 161, 22))
        self.NP_prim_phone.setObjectName("NP_prim_phone")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 281, 121, 31))
        self.label_10.setObjectName("label_10")
        self.NP_sec_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_sec_phone.setGeometry(QtCore.QRect(697, 286, 161, 22))
        self.NP_sec_phone.setObjectName("NP_sec_phone")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(559, 281, 141, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(486, 404, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(461, 404, 16, 16))
        self.label_13.setObjectName("label_13")
        self.em_name_MI = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_MI.setGeometry(QtCore.QRect(460, 425, 20, 22))
        self.em_name_MI.setObjectName("em_name_MI")
        self.em_name_last = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_last.setGeometry(QtCore.QRect(483, 425, 161, 22))
        self.em_name_last.setObjectName("em_name_last")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(577, 449, 121, 31))
        self.label_15.setObjectName("label_15")
        self.em_sex_M = QtWidgets.QRadioButton(self.centralwidget)
        self.em_sex_M.setGeometry(QtCore.QRect(708, 425, 51, 20))
        self.em_sex_M.setObjectName("em_sex_M")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(296, 405, 55, 16))
        self.label_17.setObjectName("label_17")
        self.em_sex_F = QtWidgets.QRadioButton(self.centralwidget)
        self.em_sex_F.setGeometry(QtCore.QRect(761, 426, 51, 20))
        self.em_sex_F.setObjectName("em_sex_F")
        self.em_name_first = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_first.setGeometry(QtCore.QRect(296, 425, 161, 22))
        self.em_name_first.setObjectName("em_name_first")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(241, 419, 51, 31))
        self.label_19.setObjectName("label_19")
        self.newPatientLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel_2.setGeometry(QtCore.QRect(390, 335, 301, 51))
        self.newPatientLabel_2.setObjectName("newPatientLabel_2")
        self.em_prim_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.em_prim_phone.setGeometry(QtCore.QRect(697, 454, 161, 22))
        self.em_prim_phone.setObjectName("em_prim_phone")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(660, 420, 51, 31))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(241, 448, 181, 31))
        self.label_14.setObjectName("label_14")
        self.em_relationship = QtWidgets.QLineEdit(self.centralwidget)
        self.em_relationship.setGeometry(QtCore.QRect(424, 454, 151, 22))
        self.em_relationship.setObjectName("em_relationship")
        self.newPatientLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel_3.setGeometry(QtCore.QRect(379, 506, 301, 51))
        self.newPatientLabel_3.setObjectName("newPatientLabel_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(240, 570, 71, 31))
        self.label_16.setObjectName("label_16")
        self.NP_insurance = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_insurance.setGeometry(QtCore.QRect(313, 576, 211, 22))
        self.NP_insurance.setObjectName("NP_insurance")
        self.NP_memberID = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_memberID.setGeometry(QtCore.QRect(696, 576, 161, 22))
        self.NP_memberID.setObjectName("NP_memberID")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(600, 571, 91, 31))
        self.label_23.setObjectName("label_23")
        self.NP_create = QtWidgets.QPushButton(self.centralwidget)
        self.NP_create.setGeometry(QtCore.QRect(240, 610, 93, 28))
        self.NP_create.setObjectName("NP_create")
        self.NP_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.NP_cancel.setGeometry(QtCore.QRect(765, 610, 93, 28))
        self.NP_cancel.setObjectName("NP_cancel")
        NPRegistration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NPRegistration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        NPRegistration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NPRegistration)
        self.statusbar.setObjectName("statusbar")
        NPRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(NPRegistration)
        QtCore.QMetaObject.connectSlotsByName(NPRegistration)

    def retranslateUi(self, NPRegistration):
        _translate = QtCore.QCoreApplication.translate
        NPRegistration.setWindowTitle(_translate("NPRegistration", "New Patient Registration Form"))
        self.newPatientLabel.setText(_translate("NPRegistration", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">New Patient Registration</span></p></body></html>"))
        self.label.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.label_2.setText(_translate("NPRegistration", "First"))
        self.label_3.setText(_translate("NPRegistration", "MI"))
        self.label_4.setText(_translate("NPRegistration", "Last"))
        self.label_5.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">DOB:</span></p></body></html>"))
        self.label_6.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Sex:</span></p></body></html>"))
        self.NP_sex_M.setText(_translate("NPRegistration", "M"))
        self.NP_sex_F.setText(_translate("NPRegistration", "F"))
        self.label_7.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Address:</span></p></body></html>"))
        self.label_8.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">City/State:</span></p></body></html>"))
        self.NP_state.setItemText(0, _translate("NPRegistration", "--"))
        self.NP_state.setItemText(1, _translate("NPRegistration", "AL"))
        self.NP_state.setItemText(2, _translate("NPRegistration", "AK"))
        self.NP_state.setItemText(3, _translate("NPRegistration", "AZ"))
        self.NP_state.setItemText(4, _translate("NPRegistration", "AR"))
        self.NP_state.setItemText(5, _translate("NPRegistration", "CA"))
        self.NP_state.setItemText(6, _translate("NPRegistration", "CO"))
        self.NP_state.setItemText(7, _translate("NPRegistration", "CT"))
        self.NP_state.setItemText(8, _translate("NPRegistration", "DE"))
        self.NP_state.setItemText(9, _translate("NPRegistration", "FL"))
        self.NP_state.setItemText(10, _translate("NPRegistration", "GA"))
        self.NP_state.setItemText(11, _translate("NPRegistration", "HI"))
        self.NP_state.setItemText(12, _translate("NPRegistration", "ID"))
        self.NP_state.setItemText(13, _translate("NPRegistration", "IL"))
        self.NP_state.setItemText(14, _translate("NPRegistration", "IN"))
        self.NP_state.setItemText(15, _translate("NPRegistration", "IA"))
        self.NP_state.setItemText(16, _translate("NPRegistration", "KS"))
        self.NP_state.setItemText(17, _translate("NPRegistration", "KY"))
        self.NP_state.setItemText(18, _translate("NPRegistration", "LA"))
        self.NP_state.setItemText(19, _translate("NPRegistration", "ME"))
        self.NP_state.setItemText(20, _translate("NPRegistration", "MD"))
        self.NP_state.setItemText(21, _translate("NPRegistration", "MA"))
        self.NP_state.setItemText(22, _translate("NPRegistration", "MI"))
        self.NP_state.setItemText(23, _translate("NPRegistration", "MN"))
        self.NP_state.setItemText(24, _translate("NPRegistration", "MS"))
        self.NP_state.setItemText(25, _translate("NPRegistration", "MO"))
        self.NP_state.setItemText(26, _translate("NPRegistration", "MT"))
        self.NP_state.setItemText(27, _translate("NPRegistration", "NE"))
        self.NP_state.setItemText(28, _translate("NPRegistration", "NV"))
        self.NP_state.setItemText(29, _translate("NPRegistration", "NH"))
        self.NP_state.setItemText(30, _translate("NPRegistration", "NJ"))
        self.NP_state.setItemText(31, _translate("NPRegistration", "NM"))
        self.NP_state.setItemText(32, _translate("NPRegistration", "NY"))
        self.NP_state.setItemText(33, _translate("NPRegistration", "NC"))
        self.NP_state.setItemText(34, _translate("NPRegistration", "ND"))
        self.NP_state.setItemText(35, _translate("NPRegistration", "OH"))
        self.NP_state.setItemText(36, _translate("NPRegistration", "OK"))
        self.NP_state.setItemText(37, _translate("NPRegistration", "OR"))
        self.NP_state.setItemText(38, _translate("NPRegistration", "PA"))
        self.NP_state.setItemText(39, _translate("NPRegistration", "RI"))
        self.NP_state.setItemText(40, _translate("NPRegistration", "SC"))
        self.NP_state.setItemText(41, _translate("NPRegistration", "SD"))
        self.NP_state.setItemText(42, _translate("NPRegistration", "TN"))
        self.NP_state.setItemText(43, _translate("NPRegistration", "TX"))
        self.NP_state.setItemText(44, _translate("NPRegistration", "UT"))
        self.NP_state.setItemText(45, _translate("NPRegistration", "VT"))
        self.NP_state.setItemText(46, _translate("NPRegistration", "VA"))
        self.NP_state.setItemText(47, _translate("NPRegistration", "WA"))
        self.NP_state.setItemText(48, _translate("NPRegistration", "WV"))
        self.NP_state.setItemText(49, _translate("NPRegistration", "WI"))
        self.NP_state.setItemText(50, _translate("NPRegistration", "WY"))
        self.NP_state.setItemText(51, _translate("NPRegistration", "GU"))
        self.NP_state.setItemText(52, _translate("NPRegistration", "PR"))
        self.NP_state.setItemText(53, _translate("NPRegistration", "VI"))
        self.label_9.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">ZIP:</span></p></body></html>"))
        self.label_10.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Primary Phone:</span></p></body></html>"))
        self.label_11.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Secondary Phone:</span></p></body></html>"))
        self.label_12.setText(_translate("NPRegistration", "Last"))
        self.label_13.setText(_translate("NPRegistration", "MI"))
        self.label_15.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Primary Phone:</span></p></body></html>"))
        self.em_sex_M.setText(_translate("NPRegistration", "M"))
        self.label_17.setText(_translate("NPRegistration", "First"))
        self.em_sex_F.setText(_translate("NPRegistration", "F"))
        self.label_19.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.newPatientLabel_2.setText(_translate("NPRegistration", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Emergency Contact</span></p></body></html>"))
        self.label_21.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Sex:</span></p></body></html>"))
        self.label_14.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Relationship to Patient:</span></p></body></html>"))
        self.newPatientLabel_3.setText(_translate("NPRegistration", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Insurance Info</span></p></body></html>"))
        self.label_16.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Provider:</span></p></body></html>"))
        self.label_23.setText(_translate("NPRegistration", "<html><head/><body><p><span style=\" font-size:10pt;\">Member ID:</span></p></body></html>"))
        self.NP_create.setText(_translate("NPRegistration", "Create Profile"))
        self.NP_cancel.setText(_translate("NPRegistration", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    NPRegistration = QtWidgets.QMainWindow()
    ui = Ui_NP_Registration()
    ui.setupUi(NPRegistration)
    NPRegistration.show()
    sys.exit(app.exec_())
