# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_patient_registration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newPatientLabel = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel.setGeometry(QtCore.QRect(240, 30, 301, 51))
        self.newPatientLabel.setObjectName("newPatientLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(91, 114, 51, 31))
        self.label.setObjectName("label")
        self.NP_name_first = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_first.setGeometry(QtCore.QRect(146, 120, 161, 22))
        self.NP_name_first.setObjectName("NP_name_first")
        self.NP_name_MI = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_MI.setGeometry(QtCore.QRect(310, 120, 20, 22))
        self.NP_name_MI.setObjectName("NP_name_MI")
        self.NP_name_last = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_name_last.setGeometry(QtCore.QRect(333, 120, 161, 22))
        self.NP_name_last.setObjectName("NP_name_last")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(146, 100, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(311, 99, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(336, 99, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(501, 114, 51, 31))
        self.label_5.setObjectName("label_5")
        self.NP_DOB = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_DOB.setGeometry(QtCore.QRect(547, 119, 161, 22))
        self.NP_DOB.setObjectName("NP_DOB")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(91, 150, 51, 31))
        self.label_6.setObjectName("label_6")
        self.NP_sex_M = QtWidgets.QRadioButton(self.centralwidget)
        self.NP_sex_M.setGeometry(QtCore.QRect(139, 155, 51, 20))
        self.NP_sex_M.setObjectName("NP_sex_M")
        self.NP_sex_F = QtWidgets.QRadioButton(self.centralwidget)
        self.NP_sex_F.setGeometry(QtCore.QRect(192, 156, 51, 20))
        self.NP_sex_F.setObjectName("NP_sex_F")
        self.NP_address = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_address.setGeometry(QtCore.QRect(337, 156, 371, 22))
        self.NP_address.setObjectName("NP_address")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(264, 150, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(89, 184, 81, 31))
        self.label_8.setObjectName("label_8")
        self.NP_city = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_city.setGeometry(QtCore.QRect(180, 190, 161, 22))
        self.NP_city.setObjectName("NP_city")
        self.NP_state = QtWidgets.QComboBox(self.centralwidget)
        self.NP_state.setGeometry(QtCore.QRect(350, 190, 51, 22))
        self.NP_state.setObjectName("NP_state")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_state.addItem("")
        self.NP_zip = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_zip.setGeometry(QtCore.QRect(547, 190, 161, 22))
        self.NP_zip.setObjectName("NP_zip")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(503, 185, 51, 31))
        self.label_9.setObjectName("label_9")
        self.NP_prim_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_prim_phone.setGeometry(QtCore.QRect(210, 225, 161, 22))
        self.NP_prim_phone.setObjectName("NP_prim_phone")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 220, 121, 31))
        self.label_10.setObjectName("label_10")
        self.NP_sec_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_sec_phone.setGeometry(QtCore.QRect(547, 225, 161, 22))
        self.NP_sec_phone.setObjectName("NP_sec_phone")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(409, 220, 141, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(336, 343, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(311, 343, 16, 16))
        self.label_13.setObjectName("label_13")
        self.em_DOB = QtWidgets.QLineEdit(self.centralwidget)
        self.em_DOB.setGeometry(QtCore.QRect(547, 363, 161, 22))
        self.em_DOB.setObjectName("em_DOB")
        self.em_name_MI = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_MI.setGeometry(QtCore.QRect(310, 364, 20, 22))
        self.em_name_MI.setObjectName("em_name_MI")
        self.em_name_last = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_last.setGeometry(QtCore.QRect(333, 364, 161, 22))
        self.em_name_last.setObjectName("em_name_last")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 425, 121, 31))
        self.label_15.setObjectName("label_15")
        self.em_sex_M = QtWidgets.QRadioButton(self.centralwidget)
        self.em_sex_M.setGeometry(QtCore.QRect(139, 399, 51, 20))
        self.em_sex_M.setObjectName("em_sex_M")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(146, 344, 55, 16))
        self.label_17.setObjectName("label_17")
        self.em_sex_F = QtWidgets.QRadioButton(self.centralwidget)
        self.em_sex_F.setGeometry(QtCore.QRect(192, 400, 51, 20))
        self.em_sex_F.setObjectName("em_sex_F")
        self.em_name_first = QtWidgets.QLineEdit(self.centralwidget)
        self.em_name_first.setGeometry(QtCore.QRect(146, 364, 161, 22))
        self.em_name_first.setObjectName("em_name_first")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(91, 358, 51, 31))
        self.label_19.setObjectName("label_19")
        self.em_sec_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.em_sec_phone.setGeometry(QtCore.QRect(547, 430, 161, 22))
        self.em_sec_phone.setObjectName("em_sec_phone")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(409, 425, 141, 31))
        self.label_20.setObjectName("label_20")
        self.newPatientLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel_2.setGeometry(QtCore.QRect(240, 274, 301, 51))
        self.newPatientLabel_2.setObjectName("newPatientLabel_2")
        self.em_prim_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.em_prim_phone.setGeometry(QtCore.QRect(210, 430, 161, 22))
        self.em_prim_phone.setObjectName("em_prim_phone")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(91, 394, 51, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(501, 358, 51, 31))
        self.label_22.setObjectName("label_22")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(264, 391, 181, 31))
        self.label_14.setObjectName("label_14")
        self.em_relationship = QtWidgets.QLineEdit(self.centralwidget)
        self.em_relationship.setGeometry(QtCore.QRect(447, 397, 261, 22))
        self.em_relationship.setObjectName("em_relationship")
        self.newPatientLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.newPatientLabel_3.setGeometry(QtCore.QRect(229, 480, 301, 51))
        self.newPatientLabel_3.setObjectName("newPatientLabel_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(90, 544, 71, 31))
        self.label_16.setObjectName("label_16")
        self.NP_insurance = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_insurance.setGeometry(QtCore.QRect(163, 550, 211, 22))
        self.NP_insurance.setObjectName("NP_insurance")
        self.NP_memberID = QtWidgets.QLineEdit(self.centralwidget)
        self.NP_memberID.setGeometry(QtCore.QRect(546, 550, 161, 22))
        self.NP_memberID.setObjectName("NP_memberID")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(450, 545, 91, 31))
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newPatientLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">New Patient Registration</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "First"))
        self.label_3.setText(_translate("MainWindow", "MI"))
        self.label_4.setText(_translate("MainWindow", "Last"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">DOB:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Sex:</span></p></body></html>"))
        self.NP_sex_M.setText(_translate("MainWindow", "M"))
        self.NP_sex_F.setText(_translate("MainWindow", "F"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Address:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">City/State:</span></p></body></html>"))
        self.NP_state.setItemText(0, _translate("MainWindow", "--"))
        self.NP_state.setItemText(1, _translate("MainWindow", "AL"))
        self.NP_state.setItemText(2, _translate("MainWindow", "AK"))
        self.NP_state.setItemText(3, _translate("MainWindow", "AZ"))
        self.NP_state.setItemText(4, _translate("MainWindow", "AR"))
        self.NP_state.setItemText(5, _translate("MainWindow", "CA"))
        self.NP_state.setItemText(6, _translate("MainWindow", "CO"))
        self.NP_state.setItemText(7, _translate("MainWindow", "CT"))
        self.NP_state.setItemText(8, _translate("MainWindow", "DE"))
        self.NP_state.setItemText(9, _translate("MainWindow", "FL"))
        self.NP_state.setItemText(10, _translate("MainWindow", "GA"))
        self.NP_state.setItemText(11, _translate("MainWindow", "HI"))
        self.NP_state.setItemText(12, _translate("MainWindow", "ID"))
        self.NP_state.setItemText(13, _translate("MainWindow", "IL"))
        self.NP_state.setItemText(14, _translate("MainWindow", "IN"))
        self.NP_state.setItemText(15, _translate("MainWindow", "IA"))
        self.NP_state.setItemText(16, _translate("MainWindow", "KS"))
        self.NP_state.setItemText(17, _translate("MainWindow", "KY"))
        self.NP_state.setItemText(18, _translate("MainWindow", "LA"))
        self.NP_state.setItemText(19, _translate("MainWindow", "ME"))
        self.NP_state.setItemText(20, _translate("MainWindow", "MD"))
        self.NP_state.setItemText(21, _translate("MainWindow", "MA"))
        self.NP_state.setItemText(22, _translate("MainWindow", "MI"))
        self.NP_state.setItemText(23, _translate("MainWindow", "MN"))
        self.NP_state.setItemText(24, _translate("MainWindow", "MS"))
        self.NP_state.setItemText(25, _translate("MainWindow", "MO"))
        self.NP_state.setItemText(26, _translate("MainWindow", "MT"))
        self.NP_state.setItemText(27, _translate("MainWindow", "NE"))
        self.NP_state.setItemText(28, _translate("MainWindow", "NV"))
        self.NP_state.setItemText(29, _translate("MainWindow", "NH"))
        self.NP_state.setItemText(30, _translate("MainWindow", "NJ"))
        self.NP_state.setItemText(31, _translate("MainWindow", "NM"))
        self.NP_state.setItemText(32, _translate("MainWindow", "NY"))
        self.NP_state.setItemText(33, _translate("MainWindow", "NC"))
        self.NP_state.setItemText(34, _translate("MainWindow", "ND"))
        self.NP_state.setItemText(35, _translate("MainWindow", "OH"))
        self.NP_state.setItemText(36, _translate("MainWindow", "OK"))
        self.NP_state.setItemText(37, _translate("MainWindow", "OR"))
        self.NP_state.setItemText(38, _translate("MainWindow", "PA"))
        self.NP_state.setItemText(39, _translate("MainWindow", "RI"))
        self.NP_state.setItemText(40, _translate("MainWindow", "SC"))
        self.NP_state.setItemText(41, _translate("MainWindow", "SD"))
        self.NP_state.setItemText(42, _translate("MainWindow", "TN"))
        self.NP_state.setItemText(43, _translate("MainWindow", "TX"))
        self.NP_state.setItemText(44, _translate("MainWindow", "UT"))
        self.NP_state.setItemText(45, _translate("MainWindow", "VT"))
        self.NP_state.setItemText(46, _translate("MainWindow", "VA"))
        self.NP_state.setItemText(47, _translate("MainWindow", "WA"))
        self.NP_state.setItemText(48, _translate("MainWindow", "WV"))
        self.NP_state.setItemText(49, _translate("MainWindow", "WI"))
        self.NP_state.setItemText(50, _translate("MainWindow", "WY"))
        self.NP_state.setItemText(51, _translate("MainWindow", "GU"))
        self.NP_state.setItemText(52, _translate("MainWindow", "PR"))
        self.NP_state.setItemText(53, _translate("MainWindow", "VI"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">ZIP:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Primary Phone:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Secondary Phone:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Last"))
        self.label_13.setText(_translate("MainWindow", "MI"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Primary Phone:</span></p></body></html>"))
        self.em_sex_M.setText(_translate("MainWindow", "M"))
        self.label_17.setText(_translate("MainWindow", "First"))
        self.em_sex_F.setText(_translate("MainWindow", "F"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Secondary Phone:</span></p></body></html>"))
        self.newPatientLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Emergency Contact</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Sex:</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">DOB:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Relationship to Patient:</span></p></body></html>"))
        self.newPatientLabel_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Insurance Info</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Provider:</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Member ID:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
