# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrderTest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtWidgets import QApplication, QPushButton
from Login import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        self.labtestpage = QtWidgets.QWidget(MainWindow)
        self.labtestpage.setObjectName("labtestpage")
        self.labtesttab = QtWidgets.QTabWidget(self.labtestpage)
        self.labtesttab.setGeometry(QtCore.QRect(20, 100, 1061, 641))
        self.labtesttab.setMinimumSize(QtCore.QSize(1061, 641))
        self.labtesttab.setMaximumSize(QtCore.QSize(1061, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labtesttab.setFont(font)
        self.labtesttab.setObjectName("labtesttab")
        self.hematologiclab = QtWidgets.QWidget()
        self.hematologiclab.setObjectName("hematologiclab")
        self.in_type = QtWidgets.QComboBox(self.hematologiclab)
        self.in_type.setGeometry(QtCore.QRect(210, 40, 201, 41))
        self.in_type.setObjectName("in_type")
        self.in_type.addItem("")
        self.in_type.addItem("")
        self.in_type.addItem("")
        self.in_type.addItem("")
        self.in_type.addItem("")
        self.type = QtWidgets.QLabel(self.hematologiclab)
        self.type.setGeometry(QtCore.QRect(80, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type.setFont(font)
        self.type.setObjectName("type")
        self.in_patname = QtWidgets.QLineEdit(self.hematologiclab)
        self.in_patname.setGeometry(QtCore.QRect(210, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patname.setFont(font)
        self.in_patname.setObjectName("in_patname")
        self.patname = QtWidgets.QLabel(self.hematologiclab)
        self.patname.setGeometry(QtCore.QRect(80, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patname.setFont(font)
        self.patname.setObjectName("patname")
        self.in_patid = QtWidgets.QLineEdit(self.hematologiclab)
        self.in_patid.setGeometry(QtCore.QRect(210, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patid.setFont(font)
        self.in_patid.setObjectName("in_patid")
        self.patid = QtWidgets.QLabel(self.hematologiclab)
        self.patid.setGeometry(QtCore.QRect(80, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patid.setFont(font)
        self.patid.setObjectName("patid")
        self.notes = QtWidgets.QLabel(self.hematologiclab)
        self.notes.setGeometry(QtCore.QRect(510, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes.setFont(font)
        self.notes.setObjectName("notes")
        self.in_notes = QtWidgets.QTextEdit(self.hematologiclab)
        self.in_notes.setGeometry(QtCore.QRect(590, 200, 256, 141))
        self.in_notes.setObjectName("in_notes")
        self.dateorder = QtWidgets.QLabel(self.hematologiclab)
        self.dateorder.setGeometry(QtCore.QRect(500, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateorder.setFont(font)
        self.dateorder.setObjectName("dateorder")
        self.in_dateorder_2 = QtWidgets.QDateEdit(self.hematologiclab)
        self.in_dateorder_2.setGeometry(QtCore.QRect(640, 40, 110, 22))
        self.in_dateorder_2.setObjectName("in_dateorder_2")
        self.priority = QtWidgets.QLabel(self.hematologiclab)
        self.priority.setGeometry(QtCore.QRect(500, 80, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.priority.setFont(font)
        self.priority.setObjectName("priority")
        self.in_priority = QtWidgets.QComboBox(self.hematologiclab)
        self.in_priority.setGeometry(QtCore.QRect(640, 80, 111, 31))
        self.in_priority.setObjectName("in_priority")
        self.in_priority.addItem("")
        self.in_priority.addItem("")
        self.in_priority.addItem("")
        self.in_priority.addItem("")
        self.button_ordertest = QtWidgets.QToolButton(self.hematologiclab)
        self.button_ordertest.setGeometry(QtCore.QRect(420, 390, 111, 31))
        self.button_ordertest.setObjectName("button_ordertest")
        self.labtesttab.addTab(self.hematologiclab, "")
        self.urinetest = QtWidgets.QWidget()
        self.urinetest.setObjectName("urinetest")
        self.in_patname_2 = QtWidgets.QLineEdit(self.urinetest)
        self.in_patname_2.setGeometry(QtCore.QRect(210, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patname_2.setFont(font)
        self.in_patname_2.setObjectName("in_patname_2")
        self.in_patid_2 = QtWidgets.QLineEdit(self.urinetest)
        self.in_patid_2.setGeometry(QtCore.QRect(210, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patid_2.setFont(font)
        self.in_patid_2.setObjectName("in_patid_2")
        self.patid_2 = QtWidgets.QLabel(self.urinetest)
        self.patid_2.setGeometry(QtCore.QRect(80, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patid_2.setFont(font)
        self.patid_2.setObjectName("patid_2")
        self.notes_2 = QtWidgets.QLabel(self.urinetest)
        self.notes_2.setGeometry(QtCore.QRect(510, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes_2.setFont(font)
        self.notes_2.setObjectName("notes_2")
        self.in_notes_2 = QtWidgets.QTextEdit(self.urinetest)
        self.in_notes_2.setGeometry(QtCore.QRect(590, 200, 256, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_notes_2.setFont(font)
        self.in_notes_2.setObjectName("in_notes_2")
        self.dateorder_2 = QtWidgets.QLabel(self.urinetest)
        self.dateorder_2.setGeometry(QtCore.QRect(500, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateorder_2.setFont(font)
        self.dateorder_2.setObjectName("dateorder_2")
        self.in_type_2 = QtWidgets.QComboBox(self.urinetest)
        self.in_type_2.setGeometry(QtCore.QRect(210, 40, 201, 41))
        self.in_type_2.setObjectName("in_type_2")
        self.in_type_2.addItem("")
        self.in_type_2.addItem("")
        self.in_dateorder = QtWidgets.QDateEdit(self.urinetest)
        self.in_dateorder.setGeometry(QtCore.QRect(640, 40, 110, 22))
        self.in_dateorder.setObjectName("in_dateorder")
        self.in_priority_2 = QtWidgets.QComboBox(self.urinetest)
        self.in_priority_2.setGeometry(QtCore.QRect(640, 80, 111, 31))
        self.in_priority_2.setObjectName("in_priority_2")
        self.in_priority_2.addItem("")
        self.in_priority_2.addItem("")
        self.in_priority_2.addItem("")
        self.in_priority_2.addItem("")
        self.type_2 = QtWidgets.QLabel(self.urinetest)
        self.type_2.setGeometry(QtCore.QRect(80, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_2.setFont(font)
        self.type_2.setObjectName("type_2")
        self.patname_2 = QtWidgets.QLabel(self.urinetest)
        self.patname_2.setGeometry(QtCore.QRect(80, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patname_2.setFont(font)
        self.patname_2.setObjectName("patname_2")
        self.priority_2 = QtWidgets.QLabel(self.urinetest)
        self.priority_2.setGeometry(QtCore.QRect(500, 80, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.priority_2.setFont(font)
        self.priority_2.setObjectName("priority_2")
        self.button_ordertest_2 = QtWidgets.QToolButton(self.urinetest)
        self.button_ordertest_2.setGeometry(QtCore.QRect(420, 390, 111, 31))
        self.button_ordertest_2.setObjectName("button_ordertest_2")
        self.labtesttab.addTab(self.urinetest, "")
        self.radiologiclab = QtWidgets.QWidget()
        self.radiologiclab.setObjectName("radiologiclab")
        self.in_type_3 = QtWidgets.QComboBox(self.radiologiclab)
        self.in_type_3.setGeometry(QtCore.QRect(210, 40, 201, 41))
        self.in_type_3.setObjectName("in_type_3")
        self.in_type_3.addItem("")
        self.in_type_3.addItem("")
        self.in_type_3.addItem("")
        self.label_12 = QtWidgets.QLabel(self.radiologiclab)
        self.label_12.setGeometry(QtCore.QRect(80, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.in_priority_3 = QtWidgets.QComboBox(self.radiologiclab)
        self.in_priority_3.setGeometry(QtCore.QRect(640, 80, 111, 31))
        self.in_priority_3.setObjectName("in_priority_3")
        self.in_priority_3.addItem("")
        self.in_priority_3.addItem("")
        self.in_priority_3.addItem("")
        self.in_priority_3.addItem("")
        self.in_notes_3 = QtWidgets.QTextEdit(self.radiologiclab)
        self.in_notes_3.setGeometry(QtCore.QRect(590, 200, 256, 141))
        self.in_notes_3.setObjectName("in_notes_3")
        self.in_dateorder_3 = QtWidgets.QDateEdit(self.radiologiclab)
        self.in_dateorder_3.setGeometry(QtCore.QRect(640, 40, 110, 22))
        self.in_dateorder_3.setObjectName("in_dateorder_3")
        self.patid_3 = QtWidgets.QLabel(self.radiologiclab)
        self.patid_3.setGeometry(QtCore.QRect(80, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patid_3.setFont(font)
        self.patid_3.setObjectName("patid_3")
        self.notes_3 = QtWidgets.QLabel(self.radiologiclab)
        self.notes_3.setGeometry(QtCore.QRect(510, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes_3.setFont(font)
        self.notes_3.setObjectName("notes_3")
        self.priority_3 = QtWidgets.QLabel(self.radiologiclab)
        self.priority_3.setGeometry(QtCore.QRect(500, 80, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.priority_3.setFont(font)
        self.priority_3.setObjectName("priority_3")
        self.in_patid_3 = QtWidgets.QLineEdit(self.radiologiclab)
        self.in_patid_3.setGeometry(QtCore.QRect(210, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patid_3.setFont(font)
        self.in_patid_3.setObjectName("in_patid_3")
        self.type_3 = QtWidgets.QLabel(self.radiologiclab)
        self.type_3.setGeometry(QtCore.QRect(80, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_3.setFont(font)
        self.type_3.setObjectName("type_3")
        self.button_ordertest_3 = QtWidgets.QToolButton(self.radiologiclab)
        self.button_ordertest_3.setGeometry(QtCore.QRect(420, 390, 111, 31))
        self.button_ordertest_3.setObjectName("button_ordertest_3")
        self.dateorder_3 = QtWidgets.QLabel(self.radiologiclab)
        self.dateorder_3.setGeometry(QtCore.QRect(500, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateorder_3.setFont(font)
        self.dateorder_3.setObjectName("dateorder_3")
        self.in_patname_3 = QtWidgets.QLineEdit(self.radiologiclab)
        self.in_patname_3.setGeometry(QtCore.QRect(210, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patname_3.setFont(font)
        self.in_patname_3.setObjectName("in_patname_3")
        self.labtesttab.addTab(self.radiologiclab, "")
        self.stooltest = QtWidgets.QWidget()
        self.stooltest.setObjectName("stooltest")
        self.in_patid_4 = QtWidgets.QLineEdit(self.stooltest)
        self.in_patid_4.setGeometry(QtCore.QRect(210, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patid_4.setFont(font)
        self.in_patid_4.setObjectName("in_patid_4")
        self.patname_3 = QtWidgets.QLabel(self.stooltest)
        self.patname_3.setGeometry(QtCore.QRect(80, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patname_3.setFont(font)
        self.patname_3.setObjectName("patname_3")
        self.patid_4 = QtWidgets.QLabel(self.stooltest)
        self.patid_4.setGeometry(QtCore.QRect(80, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.patid_4.setFont(font)
        self.patid_4.setObjectName("patid_4")
        self.in_patname_4 = QtWidgets.QLineEdit(self.stooltest)
        self.in_patname_4.setGeometry(QtCore.QRect(210, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_patname_4.setFont(font)
        self.in_patname_4.setObjectName("in_patname_4")
        self.in_notes_4 = QtWidgets.QTextEdit(self.stooltest)
        self.in_notes_4.setGeometry(QtCore.QRect(590, 200, 256, 141))
        self.in_notes_4.setObjectName("in_notes_4")
        self.in_dateorder_4 = QtWidgets.QDateEdit(self.stooltest)
        self.in_dateorder_4.setGeometry(QtCore.QRect(640, 40, 110, 22))
        self.in_dateorder_4.setObjectName("in_dateorder_4")
        self.in_priority_4 = QtWidgets.QComboBox(self.stooltest)
        self.in_priority_4.setGeometry(QtCore.QRect(640, 80, 111, 31))
        self.in_priority_4.setObjectName("in_priority_4")
        self.in_priority_4.addItem("")
        self.in_priority_4.addItem("")
        self.in_priority_4.addItem("")
        self.in_priority_4.addItem("")
        self.dateorder_4 = QtWidgets.QLabel(self.stooltest)
        self.dateorder_4.setGeometry(QtCore.QRect(500, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateorder_4.setFont(font)
        self.dateorder_4.setObjectName("dateorder_4")
        self.priority_4 = QtWidgets.QLabel(self.stooltest)
        self.priority_4.setGeometry(QtCore.QRect(500, 80, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.priority_4.setFont(font)
        self.priority_4.setObjectName("priority_4")
        self.button_ordertest4 = QtWidgets.QToolButton(self.stooltest)
        self.button_ordertest4.setGeometry(QtCore.QRect(420, 390, 111, 31))
        self.button_ordertest4.setObjectName("button_ordertest4")
        self.type_4 = QtWidgets.QLabel(self.stooltest)
        self.type_4.setGeometry(QtCore.QRect(80, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_4.setFont(font)
        self.type_4.setObjectName("type_4")
        self.in_type_4 = QtWidgets.QComboBox(self.stooltest)
        self.in_type_4.setGeometry(QtCore.QRect(210, 40, 201, 41))
        self.in_type_4.setObjectName("in_type_4")
        self.in_type_4.addItem("")
        self.in_type_4.addItem("")
        self.notes_4 = QtWidgets.QLabel(self.stooltest)
        self.notes_4.setGeometry(QtCore.QRect(510, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes_4.setFont(font)
        self.notes_4.setObjectName("notes_4")
        self.labtesttab.addTab(self.stooltest, "")
        self.labtestheadline = QtWidgets.QTextBrowser(self.labtestpage)
        self.labtestheadline.setGeometry(QtCore.QRect(20, 20, 291, 71))
        self.labtestheadline.setObjectName("labtestheadline")
        self.button_mainmenu = QtWidgets.QToolButton(self.labtestpage)
        self.button_mainmenu.setGeometry(QtCore.QRect(460, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_mainmenu.setFont(font)
        self.button_mainmenu.setObjectName("button_mainmenu")
        self.button_patientprofile = QtWidgets.QToolButton(self.labtestpage)
        self.button_patientprofile.setGeometry(QtCore.QRect(590, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_patientprofile.setFont(font)
        self.button_patientprofile.setObjectName("button_patientprofile")
        self.button_teststatus = QtWidgets.QToolButton(self.labtestpage)
        self.button_teststatus.setGeometry(QtCore.QRect(720, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_teststatus.setFont(font)
        self.button_teststatus.setObjectName("button_teststatus")
        MainWindow.setCentralWidget(self.labtestpage)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.labtesttab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.in_type.setItemText(0, _translate("MainWindow", "Red blood cell"))
        self.in_type.setItemText(1, _translate("MainWindow", "White blood cell"))
        self.in_type.setItemText(2, _translate("MainWindow", "Liver function test"))
        self.in_type.setItemText(3, _translate("MainWindow", "Renal function test"))
        self.in_type.setItemText(4, _translate("MainWindow", "Electrolyte test"))
        self.type.setText(_translate("MainWindow", "Type:"))
        self.in_patname.setText(_translate("MainWindow", "Jane Doe"))
        self.patname.setText(_translate("MainWindow", "Patient Name:"))
        self.in_patid.setText(_translate("MainWindow", "jdoe102"))
        self.patid.setText(_translate("MainWindow", "Patient ID:"))
        self.notes.setText(_translate("MainWindow", "Notes:"))
        self.in_notes.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Testing for White Blood Count for patient</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.dateorder.setText(_translate("MainWindow", "Date Order:"))
        self.priority.setText(_translate("MainWindow", "Priority:"))
        self.in_priority.setItemText(0, _translate("MainWindow", "Critical"))
        self.in_priority.setItemText(1, _translate("MainWindow", "Important"))
        self.in_priority.setItemText(2, _translate("MainWindow", "Normal"))
        self.in_priority.setItemText(3, _translate("MainWindow", "Low"))
        self.button_ordertest.setText(_translate("MainWindow", "Order Test"))
        self.labtesttab.setTabText(self.labtesttab.indexOf(self.hematologiclab), _translate("MainWindow", "Hematologic Laboratory"))
        self.in_patname_2.setText(_translate("MainWindow", "Jane Doe"))
        self.in_patid_2.setText(_translate("MainWindow", "jdoe102"))
        self.patid_2.setText(_translate("MainWindow", "Patient ID:"))
        self.notes_2.setText(_translate("MainWindow", "Notes:"))
        self.in_notes_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test protein level </p></body></html>"))
        self.dateorder_2.setText(_translate("MainWindow", "Date Order:"))
        self.in_type_2.setItemText(0, _translate("MainWindow", "Dipstick "))
        self.in_type_2.setItemText(1, _translate("MainWindow", "Albumin To Creatinine Ratio(UACR)"))
        self.in_priority_2.setItemText(0, _translate("MainWindow", "Critical"))
        self.in_priority_2.setItemText(1, _translate("MainWindow", "Important"))
        self.in_priority_2.setItemText(2, _translate("MainWindow", "Normal"))
        self.in_priority_2.setItemText(3, _translate("MainWindow", "Low"))
        self.type_2.setText(_translate("MainWindow", "Type:"))
        self.patname_2.setText(_translate("MainWindow", "Patient Name:"))
        self.priority_2.setText(_translate("MainWindow", "Priority:"))
        self.button_ordertest_2.setText(_translate("MainWindow", "Order Test"))
        self.labtesttab.setTabText(self.labtesttab.indexOf(self.urinetest), _translate("MainWindow", "Urine Test"))
        self.in_type_3.setItemText(0, _translate("MainWindow", "X-Ray"))
        self.in_type_3.setItemText(1, _translate("MainWindow", "Computed Tomography (CT)"))
        self.in_type_3.setItemText(2, _translate("MainWindow", "Magnetic Resonance Image (MRI)"))
        self.label_12.setText(_translate("MainWindow", "Patient Name:"))
        self.in_priority_3.setItemText(0, _translate("MainWindow", "Critical"))
        self.in_priority_3.setItemText(1, _translate("MainWindow", "Important"))
        self.in_priority_3.setItemText(2, _translate("MainWindow", "Normal"))
        self.in_priority_3.setItemText(3, _translate("MainWindow", "Low"))
        self.in_notes_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">X-Ray around the lower abs area</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.patid_3.setText(_translate("MainWindow", "Patient ID:"))
        self.notes_3.setText(_translate("MainWindow", "Notes:"))
        self.priority_3.setText(_translate("MainWindow", "Priority:"))
        self.in_patid_3.setText(_translate("MainWindow", "jdoe102"))
        self.type_3.setText(_translate("MainWindow", "Type:"))
        self.button_ordertest_3.setText(_translate("MainWindow", "Order Test"))
        self.dateorder_3.setText(_translate("MainWindow", "Date Order:"))
        self.in_patname_3.setText(_translate("MainWindow", "Jane Doe"))
        self.labtesttab.setTabText(self.labtesttab.indexOf(self.radiologiclab), _translate("MainWindow", "Radiologic Laboratory"))
        self.in_patid_4.setText(_translate("MainWindow", "jdoe102"))
        self.patname_3.setText(_translate("MainWindow", "Patient Name:"))
        self.patid_4.setText(_translate("MainWindow", "Patient ID:"))
        self.in_patname_4.setText(_translate("MainWindow", "Jane Doe"))
        self.in_notes_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Check for presence of blood</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.in_priority_4.setItemText(0, _translate("MainWindow", "Critical"))
        self.in_priority_4.setItemText(1, _translate("MainWindow", "Important"))
        self.in_priority_4.setItemText(2, _translate("MainWindow", "Normal"))
        self.in_priority_4.setItemText(3, _translate("MainWindow", "Low"))
        self.dateorder_4.setText(_translate("MainWindow", "Date Order:"))
        self.priority_4.setText(_translate("MainWindow", "Priority:"))
        self.button_ordertest4.setText(_translate("MainWindow", "Order Test"))
        self.type_4.setText(_translate("MainWindow", "Type:"))
        self.in_type_4.setItemText(0, _translate("MainWindow", "FOBT"))
        self.in_type_4.setItemText(1, _translate("MainWindow", "DNA"))
        self.notes_4.setText(_translate("MainWindow", "Notes:"))
        self.labtesttab.setTabText(self.labtesttab.indexOf(self.stooltest), _translate("MainWindow", "Stool Test"))
        self.labtestheadline.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:26pt; font-weight:600; color:#111111; background-color:#f4f4f4;\">Laboratory Test</span></p></body></html>"))
        self.button_mainmenu.setText(_translate("MainWindow", "Main Menu"))
        self.button_patientprofile.setText(_translate("MainWindow", "Patient Profile"))
        self.button_teststatus.setText(_translate("MainWindow", "Test Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
