# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientProfile.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 256, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.patientprofilestatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.patientprofilestatus.setGeometry(QtCore.QRect(290, 20, 151, 71))
        self.patientprofilestatus.setStyleSheet("background-color:rgb(249, 255, 251)")
        self.patientprofilestatus.setObjectName("patientprofilestatus")
        self.patientprofile_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.patientprofile_tab.setGeometry(QtCore.QRect(20, 110, 1061, 641))
        self.patientprofile_tab.setMinimumSize(QtCore.QSize(1061, 641))
        self.patientprofile_tab.setMaximumSize(QtCore.QSize(1061, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.patientprofile_tab.setFont(font)
        self.patientprofile_tab.setObjectName("patientprofile_tab")
        self.PaInfo = QtWidgets.QWidget()
        self.PaInfo.setObjectName("PaInfo")
        self.in_age = QtWidgets.QLineEdit(self.PaInfo)
        self.in_age.setGeometry(QtCore.QRect(70, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_age.setFont(font)
        self.in_age.setObjectName("in_age")
        self.age = QtWidgets.QLabel(self.PaInfo)
        self.age.setGeometry(QtCore.QRect(20, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.sex = QtWidgets.QLabel(self.PaInfo)
        self.sex.setGeometry(QtCore.QRect(20, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")
        self.dob_2 = QtWidgets.QLabel(self.PaInfo)
        self.dob_2.setGeometry(QtCore.QRect(150, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dob_2.setFont(font)
        self.dob_2.setObjectName("dob_2")
        self.weight = QtWidgets.QLabel(self.PaInfo)
        self.weight.setGeometry(QtCore.QRect(150, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weight.setFont(font)
        self.weight.setObjectName("weight")
        self.in_weight = QtWidgets.QLineEdit(self.PaInfo)
        self.in_weight.setGeometry(QtCore.QRect(220, 100, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_weight.setFont(font)
        self.in_weight.setObjectName("in_weight")
        self.label_5 = QtWidgets.QLabel(self.PaInfo)
        self.label_5.setGeometry(QtCore.QRect(270, 100, 31, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.height = QtWidgets.QLabel(self.PaInfo)
        self.height.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.height.setFont(font)
        self.height.setObjectName("height")
        self.in_height = QtWidgets.QLineEdit(self.PaInfo)
        self.in_height.setGeometry(QtCore.QRect(80, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_height.setFont(font)
        self.in_height.setObjectName("in_height")
        self.street = QtWidgets.QLabel(self.PaInfo)
        self.street.setGeometry(QtCore.QRect(20, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.street.setFont(font)
        self.street.setObjectName("street")
        self.in_street = QtWidgets.QLineEdit(self.PaInfo)
        self.in_street.setGeometry(QtCore.QRect(150, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_street.setFont(font)
        self.in_street.setObjectName("in_street")
        self.city = QtWidgets.QLabel(self.PaInfo)
        self.city.setGeometry(QtCore.QRect(20, 260, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.city.setFont(font)
        self.city.setObjectName("city")
        self.in_city = QtWidgets.QLineEdit(self.PaInfo)
        self.in_city.setGeometry(QtCore.QRect(150, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_city.setFont(font)
        self.in_city.setObjectName("in_city")
        self.state = QtWidgets.QLabel(self.PaInfo)
        self.state.setGeometry(QtCore.QRect(20, 300, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.in_state = QtWidgets.QLineEdit(self.PaInfo)
        self.in_state.setGeometry(QtCore.QRect(150, 300, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_state.setFont(font)
        self.in_state.setObjectName("in_state")
        self.country = QtWidgets.QLabel(self.PaInfo)
        self.country.setGeometry(QtCore.QRect(20, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.country.setFont(font)
        self.country.setObjectName("country")
        self.in_country = QtWidgets.QLineEdit(self.PaInfo)
        self.in_country.setGeometry(QtCore.QRect(150, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_country.setFont(font)
        self.in_country.setObjectName("in_country")
        self.in_primcontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_primcontact.setGeometry(QtCore.QRect(170, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_primcontact.setFont(font)
        self.in_primcontact.setObjectName("in_primcontact")
        self.primcontact = QtWidgets.QLabel(self.PaInfo)
        self.primcontact.setGeometry(QtCore.QRect(20, 420, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.primcontact.setFont(font)
        self.primcontact.setObjectName("primcontact")
        self.in_seccontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_seccontact.setGeometry(QtCore.QRect(170, 460, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_seccontact.setFont(font)
        self.in_seccontact.setObjectName("in_seccontact")
        self.seccontact = QtWidgets.QLabel(self.PaInfo)
        self.seccontact.setGeometry(QtCore.QRect(20, 460, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.seccontact.setFont(font)
        self.seccontact.setObjectName("seccontact")
        self.in_insurance = QtWidgets.QLineEdit(self.PaInfo)
        self.in_insurance.setGeometry(QtCore.QRect(650, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_insurance.setFont(font)
        self.in_insurance.setObjectName("in_insurance")
        self.in_memid = QtWidgets.QLineEdit(self.PaInfo)
        self.in_memid.setGeometry(QtCore.QRect(650, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_memid.setFont(font)
        self.in_memid.setObjectName("in_memid")
        self.insurance = QtWidgets.QLabel(self.PaInfo)
        self.insurance.setGeometry(QtCore.QRect(500, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.insurance.setFont(font)
        self.insurance.setObjectName("insurance")
        self.memid = QtWidgets.QLabel(self.PaInfo)
        self.memid.setGeometry(QtCore.QRect(500, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.memid.setFont(font)
        self.memid.setObjectName("memid")
        self.emername = QtWidgets.QLabel(self.PaInfo)
        self.emername.setGeometry(QtCore.QRect(500, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emername.setFont(font)
        self.emername.setObjectName("emername")
        self.in_emerprimcontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emerprimcontact.setGeometry(QtCore.QRect(640, 370, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emerprimcontact.setFont(font)
        self.in_emerprimcontact.setObjectName("in_emerprimcontact")
        self.emerrela = QtWidgets.QLabel(self.PaInfo)
        self.emerrela.setGeometry(QtCore.QRect(500, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emerrela.setFont(font)
        self.emerrela.setObjectName("emerrela")
        self.in_emername = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emername.setGeometry(QtCore.QRect(640, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emername.setFont(font)
        self.in_emername.setObjectName("in_emername")
        self.label_17 = QtWidgets.QLabel(self.PaInfo)
        self.label_17.setGeometry(QtCore.QRect(500, 370, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.in_emergencyrelation = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emergencyrelation.setGeometry(QtCore.QRect(640, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emergencyrelation.setFont(font)
        self.in_emergencyrelation.setObjectName("in_emergencyrelation")
        self.EmergencyContact = QtWidgets.QLabel(self.PaInfo)
        self.EmergencyContact.setGeometry(QtCore.QRect(500, 250, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.EmergencyContact.setFont(font)
        self.EmergencyContact.setObjectName("EmergencyContact")
        self.in_sex = QtWidgets.QComboBox(self.PaInfo)
        self.in_sex.setGeometry(QtCore.QRect(70, 100, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_sex.setFont(font)
        self.in_sex.setObjectName("in_sex")
        self.in_sex.addItem("")
        self.in_sex.addItem("")
        self.in_dob = QtWidgets.QDateEdit(self.PaInfo)
        self.in_dob.setGeometry(QtCore.QRect(260, 50, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_dob.setFont(font)
        self.in_dob.setObjectName("in_dob")
        self.in_zip = QtWidgets.QLineEdit(self.PaInfo)
        self.in_zip.setGeometry(QtCore.QRect(150, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_zip.setFont(font)
        self.in_zip.setObjectName("in_zip")
        self.zip = QtWidgets.QLabel(self.PaInfo)
        self.zip.setGeometry(QtCore.QRect(20, 380, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zip.setFont(font)
        self.zip.setObjectName("zip")
        self.toolButton_3 = QtWidgets.QToolButton(self.PaInfo)
        self.toolButton_3.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")
        self.patientprofile_tab.addTab(self.PaInfo, "")
        self.MeInfo = QtWidgets.QWidget()
        self.MeInfo.setObjectName("MeInfo")
        self.in_medhistory = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_medhistory.setGeometry(QtCore.QRect(190, 160, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_medhistory.setFont(font)
        self.in_medhistory.setObjectName("in_medhistory")
        self.in_allergies = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_allergies.setGeometry(QtCore.QRect(190, 280, 271, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_allergies.setFont(font)
        self.in_allergies.setObjectName("in_allergies")
        self.in_reqtest = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_reqtest.setGeometry(QtCore.QRect(190, 400, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_reqtest.setFont(font)
        self.in_reqtest.setObjectName("in_reqtest")
        self.in_diagnosis = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_diagnosis.setGeometry(QtCore.QRect(620, 40, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_diagnosis.setFont(font)
        self.in_diagnosis.setObjectName("in_diagnosis")
        self.in_symptoms = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_symptoms.setGeometry(QtCore.QRect(620, 170, 271, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_symptoms.setFont(font)
        self.in_symptoms.setObjectName("in_symptoms")
        self.in_medication = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_medication.setGeometry(QtCore.QRect(620, 320, 271, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_medication.setFont(font)
        self.in_medication.setObjectName("in_medication")
        self.cheifcom = QtWidgets.QLabel(self.MeInfo)
        self.cheifcom.setGeometry(QtCore.QRect(30, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cheifcom.setFont(font)
        self.cheifcom.setObjectName("cheifcom")
        self.in_chiefcom = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_chiefcom.setGeometry(QtCore.QRect(190, 40, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_chiefcom.setFont(font)
        self.in_chiefcom.setObjectName("in_chiefcom")
        self.medhistory = QtWidgets.QLabel(self.MeInfo)
        self.medhistory.setGeometry(QtCore.QRect(30, 160, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medhistory.setFont(font)
        self.medhistory.setObjectName("medhistory")
        self.allergies = QtWidgets.QLabel(self.MeInfo)
        self.allergies.setGeometry(QtCore.QRect(30, 280, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allergies.setFont(font)
        self.allergies.setObjectName("allergies")
        self.reqtest = QtWidgets.QLabel(self.MeInfo)
        self.reqtest.setGeometry(QtCore.QRect(30, 400, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.reqtest.setFont(font)
        self.reqtest.setMouseTracking(True)
        self.reqtest.setObjectName("reqtest")
        self.diagnosis = QtWidgets.QLabel(self.MeInfo)
        self.diagnosis.setGeometry(QtCore.QRect(480, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diagnosis.setFont(font)
        self.diagnosis.setObjectName("diagnosis")
        self.symptoms = QtWidgets.QLabel(self.MeInfo)
        self.symptoms.setGeometry(QtCore.QRect(480, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.symptoms.setFont(font)
        self.symptoms.setObjectName("symptoms")
        self.medication = QtWidgets.QLabel(self.MeInfo)
        self.medication.setGeometry(QtCore.QRect(480, 320, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medication.setFont(font)
        self.medication.setObjectName("medication")
        self.toolButton_4 = QtWidgets.QToolButton(self.MeInfo)
        self.toolButton_4.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.patientprofile_tab.addTab(self.MeInfo, "")
        self.ViNot = QtWidgets.QWidget()
        self.ViNot.setObjectName("ViNot")
        self.in_visitnote = QtWidgets.QPlainTextEdit(self.ViNot)
        self.in_visitnote.setGeometry(QtCore.QRect(150, 10, 741, 461))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_visitnote.setFont(font)
        self.in_visitnote.setObjectName("in_visitnote")
        self.visitnote = QtWidgets.QLabel(self.ViNot)
        self.visitnote.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.visitnote.setFont(font)
        self.visitnote.setObjectName("visitnote")
        self.toolButton_5 = QtWidgets.QToolButton(self.ViNot)
        self.toolButton_5.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        self.patientprofile_tab.addTab(self.ViNot, "")
        self.pres = QtWidgets.QWidget()
        self.pres.setObjectName("pres")
        self.prestab = QtWidgets.QTabWidget(self.pres)
        self.prestab.setGeometry(QtCore.QRect(20, 10, 891, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prestab.setFont(font)
        self.prestab.setObjectName("prestab")
        self.oralmedication = QtWidgets.QWidget()
        self.oralmedication.setObjectName("oralmedication")
        self.in_durationmed = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_durationmed.setGeometry(QtCore.QRect(200, 250, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_durationmed.setFont(font)
        self.in_durationmed.setObjectName("in_durationmed")
        self.pushButton = QtWidgets.QPushButton(self.oralmedication)
        self.pushButton.setGeometry(QtCore.QRect(510, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.medicationadvised = QtWidgets.QLabel(self.oralmedication)
        self.medicationadvised.setGeometry(QtCore.QRect(40, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medicationadvised.setFont(font)
        self.medicationadvised.setObjectName("medicationadvised")
        self.in_medicationadvised = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_medicationadvised.setGeometry(QtCore.QRect(200, 20, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_medicationadvised.setFont(font)
        self.in_medicationadvised.setObjectName("in_medicationadvised")
        self.datemed = QtWidgets.QLabel(self.oralmedication)
        self.datemed.setGeometry(QtCore.QRect(40, 190, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datemed.setFont(font)
        self.datemed.setObjectName("datemed")
        self.in_doseadvised = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_doseadvised.setGeometry(QtCore.QRect(200, 110, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_doseadvised.setFont(font)
        self.in_doseadvised.setObjectName("in_doseadvised")
        self.in_datemed = QtWidgets.QDateEdit(self.oralmedication)
        self.in_datemed.setGeometry(QtCore.QRect(200, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_datemed.setFont(font)
        self.in_datemed.setObjectName("in_datemed")
        self.durationmed = QtWidgets.QLabel(self.oralmedication)
        self.durationmed.setGeometry(QtCore.QRect(40, 250, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.durationmed.setFont(font)
        self.durationmed.setObjectName("durationmed")
        self.doseadvised = QtWidgets.QLabel(self.oralmedication)
        self.doseadvised.setGeometry(QtCore.QRect(40, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doseadvised.setFont(font)
        self.doseadvised.setObjectName("doseadvised")
        self.toolButton_7 = QtWidgets.QToolButton(self.oralmedication)
        self.toolButton_7.setGeometry(QtCore.QRect(380, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setObjectName("toolButton_7")
        self.prestab.addTab(self.oralmedication, "")
        self.injection = QtWidgets.QWidget()
        self.injection.setObjectName("injection")
        self.injectiontype = QtWidgets.QLabel(self.injection)
        self.injectiontype.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.injectiontype.setFont(font)
        self.injectiontype.setObjectName("injectiontype")
        self.in_notesinjection = QtWidgets.QTextEdit(self.injection)
        self.in_notesinjection.setGeometry(QtCore.QRect(140, 110, 256, 141))
        self.in_notesinjection.setObjectName("in_notesinjection")
        self.notes = QtWidgets.QLabel(self.injection)
        self.notes.setGeometry(QtCore.QRect(30, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes.setFont(font)
        self.notes.setObjectName("notes")
        self.in_datetakeninjection = QtWidgets.QDateEdit(self.injection)
        self.in_datetakeninjection.setGeometry(QtCore.QRect(570, 30, 110, 22))
        self.in_datetakeninjection.setObjectName("in_datetakeninjection")
        self.in_injectiontype = QtWidgets.QComboBox(self.injection)
        self.in_injectiontype.setGeometry(QtCore.QRect(140, 30, 251, 41))
        self.in_injectiontype.setObjectName("in_injectiontype")
        self.in_injectiontype.addItem("")
        self.in_injectiontype.addItem("")
        self.in_injectiontype.addItem("")
        self.datetakeninjection = QtWidgets.QLabel(self.injection)
        self.datetakeninjection.setGeometry(QtCore.QRect(430, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datetakeninjection.setFont(font)
        self.datetakeninjection.setObjectName("datetakeninjection")
        self.toolButton_6 = QtWidgets.QToolButton(self.injection)
        self.toolButton_6.setGeometry(QtCore.QRect(380, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setObjectName("toolButton_6")
        self.prestab.addTab(self.injection, "")
        self.patientprofile_tab.addTab(self.pres, "")
        self.test = QtWidgets.QWidget()
        self.test.setObjectName("test")
        self.subtest = QtWidgets.QTabWidget(self.test)
        self.subtest.setGeometry(QtCore.QRect(20, 20, 871, 481))
        self.subtest.setObjectName("subtest")
        self.bloodtest = QtWidgets.QWidget()
        self.bloodtest.setObjectName("bloodtest")
        self.label_31 = QtWidgets.QLabel(self.bloodtest)
        self.label_31.setGeometry(QtCore.QRect(120, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.creatinine = QtWidgets.QLineEdit(self.bloodtest)
        self.creatinine.setGeometry(QtCore.QRect(250, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.creatinine.setFont(font)
        self.creatinine.setObjectName("creatinine")
        self.hemoglobin = QtWidgets.QLineEdit(self.bloodtest)
        self.hemoglobin.setGeometry(QtCore.QRect(250, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hemoglobin.setFont(font)
        self.hemoglobin.setObjectName("hemoglobin")
        self.label_32 = QtWidgets.QLabel(self.bloodtest)
        self.label_32.setGeometry(QtCore.QRect(120, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.bloodtest)
        self.label_33.setGeometry(QtCore.QRect(120, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.bloodtest)
        self.label_34.setGeometry(QtCore.QRect(120, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.potassium = QtWidgets.QLineEdit(self.bloodtest)
        self.potassium.setGeometry(QtCore.QRect(250, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.potassium.setFont(font)
        self.potassium.setObjectName("potassium")
        self.WBCs = QtWidgets.QLineEdit(self.bloodtest)
        self.WBCs.setGeometry(QtCore.QRect(250, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WBCs.setFont(font)
        self.WBCs.setObjectName("WBCs")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_20.setGeometry(QtCore.QRect(250, 220, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_21.setGeometry(QtCore.QRect(250, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_35 = QtWidgets.QLabel(self.bloodtest)
        self.label_35.setGeometry(QtCore.QRect(120, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.bloodtest)
        self.label_36.setGeometry(QtCore.QRect(120, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.bloodtest)
        self.label_37.setGeometry(QtCore.QRect(120, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_22.setGeometry(QtCore.QRect(250, 250, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_23.setGeometry(QtCore.QRect(250, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_38 = QtWidgets.QLabel(self.bloodtest)
        self.label_38.setGeometry(QtCore.QRect(120, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.bloodtest)
        self.label_39.setGeometry(QtCore.QRect(250, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.bloodtest)
        self.label_40.setGeometry(QtCore.QRect(330, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.refpotassium = QtWidgets.QLineEdit(self.bloodtest)
        self.refpotassium.setGeometry(QtCore.QRect(330, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refpotassium.setFont(font)
        self.refpotassium.setObjectName("refpotassium")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_25.setGeometry(QtCore.QRect(330, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.refWBCs = QtWidgets.QLineEdit(self.bloodtest)
        self.refWBCs.setGeometry(QtCore.QRect(330, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refWBCs.setFont(font)
        self.refWBCs.setObjectName("refWBCs")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_27.setGeometry(QtCore.QRect(330, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_28.setGeometry(QtCore.QRect(330, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.refcreatinine = QtWidgets.QLineEdit(self.bloodtest)
        self.refcreatinine.setGeometry(QtCore.QRect(330, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refcreatinine.setFont(font)
        self.refcreatinine.setObjectName("refcreatinine")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_30.setGeometry(QtCore.QRect(330, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.refhemoglobin = QtWidgets.QLineEdit(self.bloodtest)
        self.refhemoglobin.setGeometry(QtCore.QRect(330, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refhemoglobin.setFont(font)
        self.refhemoglobin.setObjectName("refhemoglobin")
        self.label_41 = QtWidgets.QLabel(self.bloodtest)
        self.label_41.setGeometry(QtCore.QRect(120, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_32.setGeometry(QtCore.QRect(250, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_33.setGeometry(QtCore.QRect(330, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_42 = QtWidgets.QLabel(self.bloodtest)
        self.label_42.setGeometry(QtCore.QRect(120, 310, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_34.setGeometry(QtCore.QRect(250, 310, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_35.setGeometry(QtCore.QRect(330, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_43 = QtWidgets.QLabel(self.bloodtest)
        self.label_43.setGeometry(QtCore.QRect(120, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_36.setGeometry(QtCore.QRect(250, 340, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_37.setGeometry(QtCore.QRect(330, 340, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_44 = QtWidgets.QLabel(self.bloodtest)
        self.label_44.setGeometry(QtCore.QRect(120, 370, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_38.setGeometry(QtCore.QRect(250, 370, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.bloodtest)
        self.lineEdit_39.setGeometry(QtCore.QRect(330, 370, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_45 = QtWidgets.QLabel(self.bloodtest)
        self.label_45.setGeometry(QtCore.QRect(430, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.bloodtest)
        self.label_46.setGeometry(QtCore.QRect(430, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.bloodtest)
        self.label_47.setGeometry(QtCore.QRect(430, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.bloodtest)
        self.label_48.setGeometry(QtCore.QRect(430, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.bloodtest)
        self.label_49.setGeometry(QtCore.QRect(430, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.bloodtest)
        self.label_50.setGeometry(QtCore.QRect(430, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.bloodtest)
        self.label_51.setGeometry(QtCore.QRect(430, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.bloodtest)
        self.label_52.setGeometry(QtCore.QRect(430, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.bloodtest)
        self.label_53.setGeometry(QtCore.QRect(430, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.bloodtest)
        self.label_54.setGeometry(QtCore.QRect(430, 310, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.bloodtest)
        self.label_55.setGeometry(QtCore.QRect(430, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.bloodtest)
        self.label_56.setGeometry(QtCore.QRect(430, 370, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.subtest.addTab(self.bloodtest, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.subtest.addTab(self.tab_3, "")
        self.patientprofile_tab.addTab(self.test, "")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(460, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(590, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(720, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_9.setGeometry(QtCore.QRect(850, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_9.setFont(font)
        self.toolButton_9.setObjectName("toolButton_9")
        self.patientprofile_tab.raise_()
        self.textBrowser.raise_()
        self.patientprofilestatus.raise_()
        self.toolButton.raise_()
        self.toolButton_2.raise_()
        self.toolButton_8.raise_()
        self.toolButton_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.patientprofile_tab.setCurrentIndex(0)
        self.prestab.setCurrentIndex(1)
        self.subtest.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jane Doe</p></body></html>"))
        self.patientprofilestatus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Patient ID: jdoe102</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Date Created: 07/18/19</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Last Updated: 05/05/20</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Date Visit: 07/22/19</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7pt;\"><br /></p></body></html>"))
        self.PaInfo.setAccessibleName(_translate("MainWindow", "asfa"))
        self.in_age.setText(_translate("MainWindow", "21"))
        self.age.setText(_translate("MainWindow", "Age:"))
        self.sex.setText(_translate("MainWindow", "Sex:"))
        self.dob_2.setText(_translate("MainWindow", "Date of Birth:"))
        self.weight.setText(_translate("MainWindow", "Weight:"))
        self.in_weight.setText(_translate("MainWindow", "155"))
        self.label_5.setText(_translate("MainWindow", "lbs"))
        self.height.setText(_translate("MainWindow", "Height:"))
        self.in_height.setText(_translate("MainWindow", "5\'11"))
        self.street.setText(_translate("MainWindow", "Street Address:"))
        self.in_street.setText(_translate("MainWindow", "200 Bloomfield Ave"))
        self.city.setText(_translate("MainWindow", "City/Town:"))
        self.in_city.setText(_translate("MainWindow", "West Hartford"))
        self.state.setText(_translate("MainWindow", "State:"))
        self.in_state.setText(_translate("MainWindow", "CT"))
        self.country.setText(_translate("MainWindow", "Country:"))
        self.in_country.setText(_translate("MainWindow", "United State"))
        self.in_primcontact.setText(_translate("MainWindow", "971-773-1055"))
        self.primcontact.setText(_translate("MainWindow", "Primary Contact:"))
        self.in_seccontact.setText(_translate("MainWindow", "959-965-2323"))
        self.seccontact.setText(_translate("MainWindow", "Secondary Contact:"))
        self.in_insurance.setText(_translate("MainWindow", "CIGNA"))
        self.in_memid.setText(_translate("MainWindow", "H9564123"))
        self.insurance.setText(_translate("MainWindow", "Insurance:"))
        self.memid.setText(_translate("MainWindow", "Member ID:"))
        self.emername.setText(_translate("MainWindow", "Name:"))
        self.in_emerprimcontact.setText(_translate("MainWindow", "959-556-2223"))
        self.emerrela.setText(_translate("MainWindow", "Relation:"))
        self.in_emername.setText(_translate("MainWindow", "John Doe"))
        self.label_17.setText(_translate("MainWindow", "Primary Contact:"))
        self.in_emergencyrelation.setText(_translate("MainWindow", "Brother"))
        self.EmergencyContact.setText(_translate("MainWindow", "Emergency Contact:"))
        self.in_sex.setItemText(0, _translate("MainWindow", "F"))
        self.in_sex.setItemText(1, _translate("MainWindow", "M"))
        self.in_zip.setText(_translate("MainWindow", "06117"))
        self.zip.setText(_translate("MainWindow", "Zip Code:"))
        self.toolButton_3.setText(_translate("MainWindow", "Save"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.PaInfo), _translate("MainWindow", "Patient Information"))
        self.in_medhistory.setPlainText(_translate("MainWindow", "Stomach Ulcer \n"
"Chronic head pain\n"
""))
        self.in_allergies.setPlainText(_translate("MainWindow", "Seafood"))
        self.in_reqtest.setPlainText(_translate("MainWindow", "Stool Test\n"
"Blood Test\n"
"Rectal Examination\n"
""))
        self.in_diagnosis.setPlainText(_translate("MainWindow", "Tape Worm\n"
"\n"
""))
        self.in_symptoms.setPlainText(_translate("MainWindow", "Cough\n"
"Fever\n"
"Infection \n"
""))
        self.in_medication.setPlainText(_translate("MainWindow", "Avid\n"
"Anti-biotics\n"
""))
        self.cheifcom.setText(_translate("MainWindow", "Chief Complaint:"))
        self.in_chiefcom.setPlainText(_translate("MainWindow", "Stomach Pain\n"
"Loss of Weight\n"
"Dizzy\n"
"Light Headed\n"
"\n"
"\n"
""))
        self.medhistory.setText(_translate("MainWindow", "Medical History"))
        self.allergies.setText(_translate("MainWindow", "Allergies"))
        self.reqtest.setText(_translate("MainWindow", "Requested Test:"))
        self.diagnosis.setText(_translate("MainWindow", "Diagnosis:"))
        self.symptoms.setText(_translate("MainWindow", "Symptoms:"))
        self.medication.setText(_translate("MainWindow", "Medication:"))
        self.toolButton_4.setText(_translate("MainWindow", "Save"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.MeInfo), _translate("MainWindow", "Medical Information"))
        self.in_visitnote.setPlainText(_translate("MainWindow", "Patient prefer to have a female doctor & a specialist\n"
""))
        self.visitnote.setText(_translate("MainWindow", "Visit Notes:"))
        self.toolButton_5.setText(_translate("MainWindow", "Save"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.ViNot), _translate("MainWindow", "Visit Notes"))
        self.in_durationmed.setPlainText(_translate("MainWindow", "2 Weeks "))
        self.pushButton.setText(_translate("MainWindow", "Print"))
        self.medicationadvised.setText(_translate("MainWindow", "Medication Advised:"))
        self.in_medicationadvised.setPlainText(_translate("MainWindow", "Cephalexin, Acetaminophen (Tylenol)"))
        self.datemed.setText(_translate("MainWindow", "Date:"))
        self.in_doseadvised.setPlainText(_translate("MainWindow", "2 times daily- after food"))
        self.durationmed.setText(_translate("MainWindow", "Duration:"))
        self.doseadvised.setText(_translate("MainWindow", "Dose Advised:"))
        self.toolButton_7.setText(_translate("MainWindow", "Save"))
        self.prestab.setTabText(self.prestab.indexOf(self.oralmedication), _translate("MainWindow", "Oral medication "))
        self.injectiontype.setText(_translate("MainWindow", "Type:"))
        self.in_notesinjection.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Testing for White Blood Count for patient</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.notes.setText(_translate("MainWindow", "Notes:"))
        self.in_injectiontype.setItemText(0, _translate("MainWindow", "Intramuscular injection (IM)"))
        self.in_injectiontype.setItemText(1, _translate("MainWindow", "Intravascular injection (IV)"))
        self.in_injectiontype.setItemText(2, _translate("MainWindow", "Subcutaneous injection (SC)"))
        self.datetakeninjection.setText(_translate("MainWindow", "Date Taken:"))
        self.toolButton_6.setText(_translate("MainWindow", "Save"))
        self.prestab.setTabText(self.prestab.indexOf(self.injection), _translate("MainWindow", "Injection"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.pres), _translate("MainWindow", "Prescriptions"))
        self.label_31.setText(_translate("MainWindow", "Hemoglobin"))
        self.creatinine.setText(_translate("MainWindow", "0.60"))
        self.hemoglobin.setText(_translate("MainWindow", "15.5"))
        self.label_32.setText(_translate("MainWindow", "Potassium"))
        self.label_33.setText(_translate("MainWindow", "Creatinine"))
        self.label_34.setText(_translate("MainWindow", "WBCs"))
        self.potassium.setText(_translate("MainWindow", "2.5"))
        self.WBCs.setText(_translate("MainWindow", "12.210"))
        self.lineEdit_20.setText(_translate("MainWindow", "155.4"))
        self.lineEdit_21.setText(_translate("MainWindow", "160"))
        self.label_35.setText(_translate("MainWindow", "Fasting Glucose"))
        self.label_36.setText(_translate("MainWindow", "Plasma ACTH"))
        self.label_37.setText(_translate("MainWindow", "Plasma cortisol"))
        self.lineEdit_22.setText(_translate("MainWindow", "398"))
        self.lineEdit_23.setText(_translate("MainWindow", "0.73"))
        self.label_38.setText(_translate("MainWindow", "Total Bilirubin"))
        self.label_39.setText(_translate("MainWindow", "Results:"))
        self.label_40.setText(_translate("MainWindow", "Reference range:"))
        self.refpotassium.setText(_translate("MainWindow", "3.5-5.1"))
        self.lineEdit_25.setText(_translate("MainWindow", "<1.2"))
        self.refWBCs.setText(_translate("MainWindow", "4.00-10.00"))
        self.lineEdit_27.setText(_translate("MainWindow", "7.2-63.3"))
        self.lineEdit_28.setText(_translate("MainWindow", "62-180"))
        self.refcreatinine.setText(_translate("MainWindow", "0.70-1.2"))
        self.lineEdit_30.setText(_translate("MainWindow", "60-100"))
        self.refhemoglobin.setText(_translate("MainWindow", "13.5-17.0"))
        self.label_41.setText(_translate("MainWindow", "Testosterone"))
        self.lineEdit_32.setText(_translate("MainWindow", "2.57"))
        self.lineEdit_33.setText(_translate("MainWindow", "4.6-31"))
        self.label_42.setText(_translate("MainWindow", "Phosphate"))
        self.lineEdit_34.setText(_translate("MainWindow", "2.6"))
        self.lineEdit_35.setText(_translate("MainWindow", "2.7-4.5"))
        self.label_43.setText(_translate("MainWindow", "Calcium"))
        self.lineEdit_36.setText(_translate("MainWindow", "8.8"))
        self.lineEdit_37.setText(_translate("MainWindow", "8.6-10.2"))
        self.label_44.setText(_translate("MainWindow", "Calcitonin"))
        self.lineEdit_38.setText(_translate("MainWindow", "272"))
        self.lineEdit_39.setText(_translate("MainWindow", "<20"))
        self.label_45.setText(_translate("MainWindow", "10^9/L"))
        self.label_46.setText(_translate("MainWindow", "g/dL"))
        self.label_47.setText(_translate("MainWindow", "mMol/L"))
        self.label_48.setText(_translate("MainWindow", "mg/dL"))
        self.label_49.setText(_translate("MainWindow", "mg/dL"))
        self.label_50.setText(_translate("MainWindow", "mg/dL"))
        self.label_51.setText(_translate("MainWindow", "ng/L"))
        self.label_52.setText(_translate("MainWindow", "ug/L"))
        self.label_53.setText(_translate("MainWindow", "nmoli/L"))
        self.label_54.setText(_translate("MainWindow", "mg/dL"))
        self.label_55.setText(_translate("MainWindow", "mg/dL"))
        self.label_56.setText(_translate("MainWindow", "<20ng/L"))
        self.subtest.setTabText(self.subtest.indexOf(self.bloodtest), _translate("MainWindow", "Blood Test"))
        self.subtest.setTabText(self.subtest.indexOf(self.tab_3), _translate("MainWindow", "Tab 2"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.test), _translate("MainWindow", "Test Result"))
        self.toolButton.setText(_translate("MainWindow", "Main Menu"))
        self.toolButton_2.setText(_translate("MainWindow", "Order Test"))
        self.toolButton_8.setText(_translate("MainWindow", "Test Status"))
        self.toolButton_9.setText(_translate("MainWindow", "Date Visit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
