# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientProfile.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientProfile(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headlinename = QtWidgets.QTextBrowser(self.centralwidget)
        self.headlinename.setGeometry(QtCore.QRect(20, 20, 256, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.headlinename.setFont(font)
        self.headlinename.setObjectName("headlinename")
        self.patientprofilestatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.patientprofilestatus.setGeometry(QtCore.QRect(290, 20, 161, 71))
        self.patientprofilestatus.setStyleSheet("background-color:rgb(249, 255, 251)")
        self.patientprofilestatus.setObjectName("patientprofilestatus")
        self.patientprofile_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.patientprofile_tab.setGeometry(QtCore.QRect(20, 110, 1061, 641))
        self.patientprofile_tab.setMinimumSize(QtCore.QSize(1061, 641))
        self.patientprofile_tab.setMaximumSize(QtCore.QSize(1061, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.patientprofile_tab.setFont(font)
        self.patientprofile_tab.setObjectName("patientprofile_tab")
        self.PaInfo = QtWidgets.QWidget()
        self.PaInfo.setObjectName("PaInfo")
        self.in_age = QtWidgets.QLineEdit(self.PaInfo)
        self.in_age.setGeometry(QtCore.QRect(70, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_age.setFont(font)
        self.in_age.setObjectName("in_age")
        self.age = QtWidgets.QLabel(self.PaInfo)
        self.age.setGeometry(QtCore.QRect(20, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.sex = QtWidgets.QLabel(self.PaInfo)
        self.sex.setGeometry(QtCore.QRect(20, 100, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")
        self.dob_2 = QtWidgets.QLabel(self.PaInfo)
        self.dob_2.setGeometry(QtCore.QRect(150, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dob_2.setFont(font)
        self.dob_2.setObjectName("dob_2")
        self.weight = QtWidgets.QLabel(self.PaInfo)
        self.weight.setGeometry(QtCore.QRect(150, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weight.setFont(font)
        self.weight.setObjectName("weight")
        self.in_weight = QtWidgets.QLineEdit(self.PaInfo)
        self.in_weight.setGeometry(QtCore.QRect(220, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_weight.setFont(font)
        self.in_weight.setObjectName("in_weight")
        self.label_5 = QtWidgets.QLabel(self.PaInfo)
        self.label_5.setGeometry(QtCore.QRect(270, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.height = QtWidgets.QLabel(self.PaInfo)
        self.height.setGeometry(QtCore.QRect(20, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.height.setFont(font)
        self.height.setObjectName("height")
        self.in_height = QtWidgets.QLineEdit(self.PaInfo)
        self.in_height.setGeometry(QtCore.QRect(100, 150, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_height.setFont(font)
        self.in_height.setObjectName("in_height")
        self.street = QtWidgets.QLabel(self.PaInfo)
        self.street.setGeometry(QtCore.QRect(20, 220, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.street.setFont(font)
        self.street.setObjectName("street")
        self.in_street = QtWidgets.QLineEdit(self.PaInfo)
        self.in_street.setGeometry(QtCore.QRect(200, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_street.setFont(font)
        self.in_street.setObjectName("in_street")
        self.city = QtWidgets.QLabel(self.PaInfo)
        self.city.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.city.setFont(font)
        self.city.setObjectName("city")
        self.in_city = QtWidgets.QLineEdit(self.PaInfo)
        self.in_city.setGeometry(QtCore.QRect(200, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_city.setFont(font)
        self.in_city.setObjectName("in_city")
        self.state = QtWidgets.QLabel(self.PaInfo)
        self.state.setGeometry(QtCore.QRect(20, 300, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.in_state = QtWidgets.QLineEdit(self.PaInfo)
        self.in_state.setGeometry(QtCore.QRect(200, 300, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_state.setFont(font)
        self.in_state.setObjectName("in_state")
        self.country = QtWidgets.QLabel(self.PaInfo)
        self.country.setGeometry(QtCore.QRect(20, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.country.setFont(font)
        self.country.setObjectName("country")
        self.in_country = QtWidgets.QLineEdit(self.PaInfo)
        self.in_country.setGeometry(QtCore.QRect(200, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_country.setFont(font)
        self.in_country.setObjectName("in_country")
        self.in_primcontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_primcontact.setGeometry(QtCore.QRect(200, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_primcontact.setFont(font)
        self.in_primcontact.setObjectName("in_primcontact")
        self.primcontact = QtWidgets.QLabel(self.PaInfo)
        self.primcontact.setGeometry(QtCore.QRect(20, 420, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.primcontact.setFont(font)
        self.primcontact.setObjectName("primcontact")
        self.in_seccontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_seccontact.setGeometry(QtCore.QRect(200, 460, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_seccontact.setFont(font)
        self.in_seccontact.setObjectName("in_seccontact")
        self.seccontact = QtWidgets.QLabel(self.PaInfo)
        self.seccontact.setGeometry(QtCore.QRect(20, 460, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.seccontact.setFont(font)
        self.seccontact.setObjectName("seccontact")
        self.in_insurance = QtWidgets.QLineEdit(self.PaInfo)
        self.in_insurance.setGeometry(QtCore.QRect(650, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_insurance.setFont(font)
        self.in_insurance.setObjectName("in_insurance")
        self.in_memid = QtWidgets.QLineEdit(self.PaInfo)
        self.in_memid.setGeometry(QtCore.QRect(650, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_memid.setFont(font)
        self.in_memid.setObjectName("in_memid")
        self.insurance = QtWidgets.QLabel(self.PaInfo)
        self.insurance.setGeometry(QtCore.QRect(500, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.insurance.setFont(font)
        self.insurance.setObjectName("insurance")
        self.memid = QtWidgets.QLabel(self.PaInfo)
        self.memid.setGeometry(QtCore.QRect(500, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.memid.setFont(font)
        self.memid.setObjectName("memid")
        self.emername = QtWidgets.QLabel(self.PaInfo)
        self.emername.setGeometry(QtCore.QRect(500, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emername.setFont(font)
        self.emername.setObjectName("emername")
        self.in_emerprimcontact = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emerprimcontact.setGeometry(QtCore.QRect(660, 370, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emerprimcontact.setFont(font)
        self.in_emerprimcontact.setObjectName("in_emerprimcontact")
        self.emerrela = QtWidgets.QLabel(self.PaInfo)
        self.emerrela.setGeometry(QtCore.QRect(500, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emerrela.setFont(font)
        self.emerrela.setObjectName("emerrela")
        self.in_emername = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emername.setGeometry(QtCore.QRect(660, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emername.setFont(font)
        self.in_emername.setObjectName("in_emername")
        self.label_17 = QtWidgets.QLabel(self.PaInfo)
        self.label_17.setGeometry(QtCore.QRect(500, 370, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.in_emergencyrelation = QtWidgets.QLineEdit(self.PaInfo)
        self.in_emergencyrelation.setGeometry(QtCore.QRect(660, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_emergencyrelation.setFont(font)
        self.in_emergencyrelation.setObjectName("in_emergencyrelation")
        self.EmergencyContact = QtWidgets.QLabel(self.PaInfo)
        self.EmergencyContact.setGeometry(QtCore.QRect(500, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.EmergencyContact.setFont(font)
        self.EmergencyContact.setObjectName("EmergencyContact")
        self.in_zip = QtWidgets.QLineEdit(self.PaInfo)
        self.in_zip.setGeometry(QtCore.QRect(200, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_zip.setFont(font)
        self.in_zip.setObjectName("in_zip")
        self.zip = QtWidgets.QLabel(self.PaInfo)
        self.zip.setGeometry(QtCore.QRect(20, 380, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.zip.setFont(font)
        self.zip.setObjectName("zip")
        self.saveButton = QtWidgets.QToolButton(self.PaInfo)
        self.saveButton.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.in_sex = QtWidgets.QLineEdit(self.PaInfo)
        self.in_sex.setGeometry(QtCore.QRect(70, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_sex.setFont(font)
        self.in_sex.setObjectName("in_sex")
        self.in_dob = QtWidgets.QLineEdit(self.PaInfo)
        self.in_dob.setGeometry(QtCore.QRect(280, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_dob.setFont(font)
        self.in_dob.setObjectName("in_dob")
        self.patientprofile_tab.addTab(self.PaInfo, "")
        self.MeInfo = QtWidgets.QWidget()
        self.MeInfo.setObjectName("MeInfo")
        self.in_medhistory = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_medhistory.setGeometry(QtCore.QRect(190, 160, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_medhistory.setFont(font)
        self.in_medhistory.setObjectName("in_medhistory")
        self.in_allergies = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_allergies.setGeometry(QtCore.QRect(190, 280, 271, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_allergies.setFont(font)
        self.in_allergies.setObjectName("in_allergies")
        self.in_reqtest = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_reqtest.setGeometry(QtCore.QRect(190, 400, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_reqtest.setFont(font)
        self.in_reqtest.setObjectName("in_reqtest")
        self.in_diagnosis = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_diagnosis.setGeometry(QtCore.QRect(620, 40, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_diagnosis.setFont(font)
        self.in_diagnosis.setObjectName("in_diagnosis")
        self.in_symptoms = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_symptoms.setGeometry(QtCore.QRect(620, 170, 271, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_symptoms.setFont(font)
        self.in_symptoms.setObjectName("in_symptoms")
        self.in_medication = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_medication.setGeometry(QtCore.QRect(620, 320, 271, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_medication.setFont(font)
        self.in_medication.setObjectName("in_medication")
        self.cheifcom = QtWidgets.QLabel(self.MeInfo)
        self.cheifcom.setGeometry(QtCore.QRect(30, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cheifcom.setFont(font)
        self.cheifcom.setObjectName("cheifcom")
        self.in_chiefcom = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.in_chiefcom.setGeometry(QtCore.QRect(190, 40, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_chiefcom.setFont(font)
        self.in_chiefcom.setObjectName("in_chiefcom")
        self.medhistory = QtWidgets.QLabel(self.MeInfo)
        self.medhistory.setGeometry(QtCore.QRect(30, 160, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medhistory.setFont(font)
        self.medhistory.setObjectName("medhistory")
        self.allergies = QtWidgets.QLabel(self.MeInfo)
        self.allergies.setGeometry(QtCore.QRect(30, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allergies.setFont(font)
        self.allergies.setObjectName("allergies")
        self.reqtest = QtWidgets.QLabel(self.MeInfo)
        self.reqtest.setGeometry(QtCore.QRect(30, 400, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.reqtest.setFont(font)
        self.reqtest.setMouseTracking(True)
        self.reqtest.setObjectName("reqtest")
        self.diagnosis = QtWidgets.QLabel(self.MeInfo)
        self.diagnosis.setGeometry(QtCore.QRect(480, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diagnosis.setFont(font)
        self.diagnosis.setObjectName("diagnosis")
        self.symptoms = QtWidgets.QLabel(self.MeInfo)
        self.symptoms.setGeometry(QtCore.QRect(480, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.symptoms.setFont(font)
        self.symptoms.setObjectName("symptoms")
        self.medication = QtWidgets.QLabel(self.MeInfo)
        self.medication.setGeometry(QtCore.QRect(480, 320, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medication.setFont(font)
        self.medication.setObjectName("medication")
        self.toolButton_4 = QtWidgets.QToolButton(self.MeInfo)
        self.toolButton_4.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.doctor = QtWidgets.QLabel(self.MeInfo)
        self.doctor.setGeometry(QtCore.QRect(490, 440, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doctor.setFont(font)
        self.doctor.setObjectName("doctor")
        self.in_doctor = QtWidgets.QLineEdit(self.MeInfo)
        self.in_doctor.setGeometry(QtCore.QRect(640, 440, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_doctor.setFont(font)
        self.in_doctor.setObjectName("in_doctor")
        self.patientprofile_tab.addTab(self.MeInfo, "")
        self.ViNot = QtWidgets.QWidget()
        self.ViNot.setObjectName("ViNot")
        self.in_visitnote = QtWidgets.QPlainTextEdit(self.ViNot)
        self.in_visitnote.setGeometry(QtCore.QRect(150, 10, 741, 461))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.in_visitnote.setFont(font)
        self.in_visitnote.setObjectName("in_visitnote")
        self.visitnote = QtWidgets.QLabel(self.ViNot)
        self.visitnote.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.visitnote.setFont(font)
        self.visitnote.setObjectName("visitnote")
        self.toolButton_5 = QtWidgets.QToolButton(self.ViNot)
        self.toolButton_5.setGeometry(QtCore.QRect(410, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        self.patientprofile_tab.addTab(self.ViNot, "")
        self.pres = QtWidgets.QWidget()
        self.pres.setObjectName("pres")
        self.prestab = QtWidgets.QTabWidget(self.pres)
        self.prestab.setGeometry(QtCore.QRect(20, 10, 891, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prestab.setFont(font)
        self.prestab.setObjectName("prestab")
        self.oralmedication = QtWidgets.QWidget()
        self.oralmedication.setObjectName("oralmedication")
        self.in_durationmed = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_durationmed.setGeometry(QtCore.QRect(220, 250, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_durationmed.setFont(font)
        self.in_durationmed.setObjectName("in_durationmed")
        self.pushButton = QtWidgets.QPushButton(self.oralmedication)
        self.pushButton.setGeometry(QtCore.QRect(510, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.medicationadvised = QtWidgets.QLabel(self.oralmedication)
        self.medicationadvised.setGeometry(QtCore.QRect(40, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medicationadvised.setFont(font)
        self.medicationadvised.setObjectName("medicationadvised")
        self.in_medicationadvised = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_medicationadvised.setGeometry(QtCore.QRect(220, 20, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_medicationadvised.setFont(font)
        self.in_medicationadvised.setObjectName("in_medicationadvised")
        self.datemed = QtWidgets.QLabel(self.oralmedication)
        self.datemed.setGeometry(QtCore.QRect(40, 190, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datemed.setFont(font)
        self.datemed.setObjectName("datemed")
        self.in_doseadvised = QtWidgets.QPlainTextEdit(self.oralmedication)
        self.in_doseadvised.setGeometry(QtCore.QRect(220, 110, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_doseadvised.setFont(font)
        self.in_doseadvised.setObjectName("in_doseadvised")
        self.durationmed = QtWidgets.QLabel(self.oralmedication)
        self.durationmed.setGeometry(QtCore.QRect(40, 250, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.durationmed.setFont(font)
        self.durationmed.setObjectName("durationmed")
        self.doseadvised = QtWidgets.QLabel(self.oralmedication)
        self.doseadvised.setGeometry(QtCore.QRect(40, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doseadvised.setFont(font)
        self.doseadvised.setObjectName("doseadvised")
        self.toolButton_7 = QtWidgets.QToolButton(self.oralmedication)
        self.toolButton_7.setGeometry(QtCore.QRect(380, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setObjectName("toolButton_7")
        self.in_datemed = QtWidgets.QLineEdit(self.oralmedication)
        self.in_datemed.setGeometry(QtCore.QRect(220, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_datemed.setFont(font)
        self.in_datemed.setObjectName("in_datemed")
        self.prestab.addTab(self.oralmedication, "")
        self.injection = QtWidgets.QWidget()
        self.injection.setObjectName("injection")
        self.injectiontype = QtWidgets.QLabel(self.injection)
        self.injectiontype.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.injectiontype.setFont(font)
        self.injectiontype.setObjectName("injectiontype")
        self.in_notesinjection = QtWidgets.QTextEdit(self.injection)
        self.in_notesinjection.setGeometry(QtCore.QRect(140, 110, 256, 141))
        self.in_notesinjection.setObjectName("in_notesinjection")
        self.notes = QtWidgets.QLabel(self.injection)
        self.notes.setGeometry(QtCore.QRect(30, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.notes.setFont(font)
        self.notes.setObjectName("notes")
        self.in_injectiontype = QtWidgets.QComboBox(self.injection)
        self.in_injectiontype.setGeometry(QtCore.QRect(140, 30, 291, 41))
        self.in_injectiontype.setObjectName("in_injectiontype")
        self.in_injectiontype.addItem("")
        self.in_injectiontype.addItem("")
        self.in_injectiontype.addItem("")
        self.datetakeninjection = QtWidgets.QLabel(self.injection)
        self.datetakeninjection.setGeometry(QtCore.QRect(480, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datetakeninjection.setFont(font)
        self.datetakeninjection.setObjectName("datetakeninjection")
        self.toolButton_6 = QtWidgets.QToolButton(self.injection)
        self.toolButton_6.setGeometry(QtCore.QRect(380, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setObjectName("toolButton_6")
        self.in_datetakeninjection = QtWidgets.QLineEdit(self.injection)
        self.in_datetakeninjection.setGeometry(QtCore.QRect(600, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.in_datetakeninjection.setFont(font)
        self.in_datetakeninjection.setObjectName("in_datetakeninjection")
        self.prestab.addTab(self.injection, "")
        self.patientprofile_tab.addTab(self.pres, "")
        self.test = QtWidgets.QWidget()
        self.test.setObjectName("test")
        self.in_injectiontype_2 = QtWidgets.QComboBox(self.test)
        self.in_injectiontype_2.setGeometry(QtCore.QRect(280, 30, 291, 41))
        self.in_injectiontype_2.setObjectName("in_injectiontype_2")
        self.in_injectiontype_2.addItem("")
        self.injectiontype_2 = QtWidgets.QLabel(self.test)
        self.injectiontype_2.setGeometry(QtCore.QRect(50, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.injectiontype_2.setFont(font)
        self.injectiontype_2.setObjectName("injectiontype_2")
        self.button_iopenresult = QtWidgets.QToolButton(self.test)
        self.button_iopenresult.setGeometry(QtCore.QRect(390, 160, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_iopenresult.setFont(font)
        self.button_iopenresult.setObjectName("button_iopenresult")
        self.patientprofile_tab.addTab(self.test, "")
        self.button_mainmenu = QtWidgets.QToolButton(self.centralwidget)
        self.button_mainmenu.setGeometry(QtCore.QRect(460, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_mainmenu.setFont(font)
        self.button_mainmenu.setObjectName("button_mainmenu")
        self.button_ordertest = QtWidgets.QToolButton(self.centralwidget)
        self.button_ordertest.setGeometry(QtCore.QRect(590, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ordertest.setFont(font)
        self.button_ordertest.setObjectName("button_ordertest")
        self.button_teststatus = QtWidgets.QToolButton(self.centralwidget)
        self.button_teststatus.setGeometry(QtCore.QRect(720, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_teststatus.setFont(font)
        self.button_teststatus.setObjectName("button_teststatus")
        self.button_datevisit = QtWidgets.QToolButton(self.centralwidget)
        self.button_datevisit.setGeometry(QtCore.QRect(850, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_datevisit.setFont(font)
        self.button_datevisit.setObjectName("button_datevisit")
        self.patientprofile_tab.raise_()
        self.headlinename.raise_()
        self.patientprofilestatus.raise_()
        self.button_mainmenu.raise_()
        self.button_ordertest.raise_()
        self.button_teststatus.raise_()
        self.button_datevisit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.patientprofile_tab.setCurrentIndex(0)
        self.prestab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headlinename.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jane Doe</p></body></html>"))
        self.patientprofilestatus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Patient ID: jdoe102</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Date Created: 07/18/19</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Last Updated: 05/05/20</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Date Visit: 07/22/19</span></p></body></html>"))
        self.PaInfo.setAccessibleName(_translate("MainWindow", "asfa"))
        self.in_age.setText(_translate("MainWindow", "21"))
        self.age.setText(_translate("MainWindow", "Age:"))
        self.sex.setText(_translate("MainWindow", "Sex:"))
        self.dob_2.setText(_translate("MainWindow", "Date of Birth:"))
        self.weight.setText(_translate("MainWindow", "Weight:"))
        self.in_weight.setText(_translate("MainWindow", "155"))
        self.label_5.setText(_translate("MainWindow", "lbs"))
        self.height.setText(_translate("MainWindow", "Height:"))
        self.in_height.setText(_translate("MainWindow", "5\'11"))
        self.street.setText(_translate("MainWindow", "Street Address:"))
        self.in_street.setText(_translate("MainWindow", "200 Bloomfield Ave"))
        self.city.setText(_translate("MainWindow", "City/Town:"))
        self.in_city.setText(_translate("MainWindow", "West Hartford"))
        self.state.setText(_translate("MainWindow", "State:"))
        self.in_state.setText(_translate("MainWindow", "CT"))
        self.country.setText(_translate("MainWindow", "Country:"))
        self.in_country.setText(_translate("MainWindow", "United State"))
        self.in_primcontact.setText(_translate("MainWindow", "971-773-1055"))
        self.primcontact.setText(_translate("MainWindow", "Primary Contact:"))
        self.in_seccontact.setText(_translate("MainWindow", "959-965-2323"))
        self.seccontact.setText(_translate("MainWindow", "Secondary Contact:"))
        self.in_insurance.setText(_translate("MainWindow", "CIGNA"))
        self.in_memid.setText(_translate("MainWindow", "H9564123"))
        self.insurance.setText(_translate("MainWindow", "Insurance:"))
        self.memid.setText(_translate("MainWindow", "Member ID:"))
        self.emername.setText(_translate("MainWindow", "Name:"))
        self.in_emerprimcontact.setText(_translate("MainWindow", "959-556-2223"))
        self.emerrela.setText(_translate("MainWindow", "Relation:"))
        self.in_emername.setText(_translate("MainWindow", "John Doe"))
        self.label_17.setText(_translate("MainWindow", "Primary Contact:"))
        self.in_emergencyrelation.setText(_translate("MainWindow", "Brother"))
        self.EmergencyContact.setText(_translate("MainWindow", "Emergency Contact:"))
        self.in_zip.setText(_translate("MainWindow", "06117"))
        self.zip.setText(_translate("MainWindow", "Zip Code:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.in_sex.setText(_translate("MainWindow", "F"))
        self.in_dob.setText(_translate("MainWindow", "1998-07-25"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.PaInfo), _translate("MainWindow", "Patient Information"))
        self.in_medhistory.setPlainText(_translate("MainWindow", "Stomach Ulcer \n"
"Chronic head pain\n"
""))
        self.in_allergies.setPlainText(_translate("MainWindow", "Seafood"))
        self.in_reqtest.setPlainText(_translate("MainWindow", "Stool Test\n"
"Blood Test\n"
"Rectal Examination\n"
""))
        self.in_diagnosis.setPlainText(_translate("MainWindow", "Tape Worm\n"
"\n"
""))
        self.in_symptoms.setPlainText(_translate("MainWindow", "Cough\n"
"Fever\n"
"Infection \n"
""))
        self.in_medication.setPlainText(_translate("MainWindow", "Avid\n"
"Anti-biotics\n"
""))
        self.cheifcom.setText(_translate("MainWindow", "Chief Complaint:"))
        self.in_chiefcom.setPlainText(_translate("MainWindow", "Stomach Pain\n"
"Loss of Weight\n"
"Dizzy\n"
"Light Headed\n"
"\n"
"\n"
""))
        self.medhistory.setText(_translate("MainWindow", "Medical History"))
        self.allergies.setText(_translate("MainWindow", "Allergies"))
        self.reqtest.setText(_translate("MainWindow", "Requested Test:"))
        self.diagnosis.setText(_translate("MainWindow", "Diagnosis:"))
        self.symptoms.setText(_translate("MainWindow", "Symptoms:"))
        self.medication.setText(_translate("MainWindow", "Medication:"))
        self.toolButton_4.setText(_translate("MainWindow", "Save"))
        self.doctor.setText(_translate("MainWindow", "Doctor:"))
        self.in_doctor.setText(_translate("MainWindow", "Dr. Brown"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.MeInfo), _translate("MainWindow", "Medical Information"))
        self.in_visitnote.setPlainText(_translate("MainWindow", "Patient prefer to have a female doctor & a specialist\n"
""))
        self.visitnote.setText(_translate("MainWindow", "Visit Notes:"))
        self.toolButton_5.setText(_translate("MainWindow", "Save"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.ViNot), _translate("MainWindow", "Visit Notes"))
        self.in_durationmed.setPlainText(_translate("MainWindow", "2 Weeks "))
        self.pushButton.setText(_translate("MainWindow", "Print"))
        self.medicationadvised.setText(_translate("MainWindow", "Medication Advised:"))
        self.in_medicationadvised.setPlainText(_translate("MainWindow", "Cephalexin, Acetaminophen (Tylenol)"))
        self.datemed.setText(_translate("MainWindow", "Date:"))
        self.in_doseadvised.setPlainText(_translate("MainWindow", "2 times daily- after food"))
        self.durationmed.setText(_translate("MainWindow", "Duration:"))
        self.doseadvised.setText(_translate("MainWindow", "Dose Advised:"))
        self.toolButton_7.setText(_translate("MainWindow", "Save"))
        self.in_datemed.setText(_translate("MainWindow", "2019-07-25"))
        self.prestab.setTabText(self.prestab.indexOf(self.oralmedication), _translate("MainWindow", "Oral medication "))
        self.injectiontype.setText(_translate("MainWindow", "Type:"))
        self.in_notesinjection.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Testing for White Blood Count for patient</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.notes.setText(_translate("MainWindow", "Notes:"))
        self.in_injectiontype.setItemText(0, _translate("MainWindow", "Intramuscular injection (IM)"))
        self.in_injectiontype.setItemText(1, _translate("MainWindow", "Intravascular injection (IV)"))
        self.in_injectiontype.setItemText(2, _translate("MainWindow", "Subcutaneous injection (SC)"))
        self.datetakeninjection.setText(_translate("MainWindow", "Date Taken:"))
        self.toolButton_6.setText(_translate("MainWindow", "Save"))
        self.in_datetakeninjection.setText(_translate("MainWindow", "2019-07-25"))
        self.prestab.setTabText(self.prestab.indexOf(self.injection), _translate("MainWindow", "Injection"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.pres), _translate("MainWindow", "Prescriptions"))
        self.in_injectiontype_2.setItemText(0, _translate("MainWindow", "Blood Test"))
        self.injectiontype_2.setText(_translate("MainWindow", "Available results:"))
        self.button_iopenresult.setText(_translate("MainWindow", "Open Result"))
        self.patientprofile_tab.setTabText(self.patientprofile_tab.indexOf(self.test), _translate("MainWindow", "Test Result"))
        self.button_mainmenu.setText(_translate("MainWindow", "Search"))
        self.button_ordertest.setText(_translate("MainWindow", "Order Test"))
        self.button_teststatus.setText(_translate("MainWindow", "Test Status"))
        self.button_datevisit.setText(_translate("MainWindow", "Date Visit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_PatientProfile()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
