# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientProfile.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
# Sup

from PyQt5 import QtCore, QtGui, QtWidgets
from OrderTest import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 60, 256, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(290, 60, 151, 71))
        self.textBrowser_2.setStyleSheet("background-color:rgb(249, 255, 251)")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(40, 140, 971, 541))
        self.tab.setObjectName("tab")
        self.PaInfo = QtWidgets.QWidget()
        self.PaInfo.setObjectName("PaInfo")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.PaInfo)
        self.label.setGeometry(QtCore.QRect(20, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.PaInfo)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PaInfo)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.PaInfo)
        self.label_4.setGeometry(QtCore.QRect(150, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 100, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.PaInfo)
        self.label_5.setGeometry(QtCore.QRect(270, 100, 31, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.PaInfo)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.PaInfo)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.PaInfo)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.PaInfo)
        self.label_9.setGeometry(QtCore.QRect(20, 300, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 300, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.PaInfo)
        self.label_10.setGeometry(QtCore.QRect(20, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.PaInfo)
        self.label_11.setGeometry(QtCore.QRect(20, 420, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 460, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.PaInfo)
        self.label_12.setGeometry(QtCore.QRect(20, 460, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_11.setGeometry(QtCore.QRect(650, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_12.setGeometry(QtCore.QRect(650, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_13 = QtWidgets.QLabel(self.PaInfo)
        self.label_13.setGeometry(QtCore.QRect(500, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.PaInfo)
        self.label_14.setGeometry(QtCore.QRect(500, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.PaInfo)
        self.label_15.setGeometry(QtCore.QRect(500, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_13.setGeometry(QtCore.QRect(640, 370, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_16 = QtWidgets.QLabel(self.PaInfo)
        self.label_16.setGeometry(QtCore.QRect(500, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_14.setGeometry(QtCore.QRect(640, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_17 = QtWidgets.QLabel(self.PaInfo)
        self.label_17.setGeometry(QtCore.QRect(500, 370, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_15.setGeometry(QtCore.QRect(640, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_18 = QtWidgets.QLabel(self.PaInfo)
        self.label_18.setGeometry(QtCore.QRect(500, 250, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox = QtWidgets.QComboBox(self.PaInfo)
        self.comboBox.setGeometry(QtCore.QRect(70, 100, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.dob = QtWidgets.QDateEdit(self.PaInfo)
        self.dob.setGeometry(QtCore.QRect(260, 50, 110, 22))
        self.dob.setObjectName("dob")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.PaInfo)
        self.lineEdit_40.setGeometry(QtCore.QRect(150, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_57 = QtWidgets.QLabel(self.PaInfo)
        self.label_57.setGeometry(QtCore.QRect(20, 380, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.tab.addTab(self.PaInfo, "")
        self.MeInfo = QtWidgets.QWidget()
        self.MeInfo.setObjectName("MeInfo")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(190, 160, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(190, 280, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(190, 400, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(620, 40, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_6.setFont(font)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(620, 170, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(620, 320, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_8.setFont(font)
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.label_19 = QtWidgets.QLabel(self.MeInfo)
        self.label_19.setGeometry(QtCore.QRect(30, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.MeInfo)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(190, 40, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_10.setFont(font)
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.label_20 = QtWidgets.QLabel(self.MeInfo)
        self.label_20.setGeometry(QtCore.QRect(30, 160, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.MeInfo)
        self.label_21.setGeometry(QtCore.QRect(30, 280, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.MeInfo)
        self.label_22.setGeometry(QtCore.QRect(30, 400, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setMouseTracking(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.MeInfo)
        self.label_23.setGeometry(QtCore.QRect(480, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.MeInfo)
        self.label_24.setGeometry(QtCore.QRect(480, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.MeInfo)
        self.label_25.setGeometry(QtCore.QRect(480, 320, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.tab.addTab(self.MeInfo, "")
        self.ViNot = QtWidgets.QWidget()
        self.ViNot.setObjectName("ViNot")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.ViNot)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(150, 10, 741, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_26 = QtWidgets.QLabel(self.ViNot)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.tab.addTab(self.ViNot, "")
        self.pres = QtWidgets.QWidget()
        self.pres.setObjectName("pres")
        self.tabWidget = QtWidgets.QTabWidget(self.pres)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 891, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(200, 250, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_13.setFont(font)
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(230, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(40, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(200, 20, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_11.setFont(font)
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(40, 190, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(200, 110, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_12.setFont(font)
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_4)
        self.dateTimeEdit.setGeometry(QtCore.QRect(200, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(40, 250, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(40, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_58 = QtWidgets.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 110, 256, 141))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_59 = QtWidgets.QLabel(self.tab_5)
        self.label_59.setGeometry(QtCore.QRect(30, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_5)
        self.dateEdit.setGeometry(QtCore.QRect(570, 30, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 30, 251, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_60 = QtWidgets.QLabel(self.tab_5)
        self.label_60.setGeometry(QtCore.QRect(430, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab.addTab(self.pres, "")
        self.test = QtWidgets.QWidget()
        self.test.setObjectName("test")
        self.subtest = QtWidgets.QTabWidget(self.test)
        self.subtest.setGeometry(QtCore.QRect(20, 20, 871, 481))
        self.subtest.setObjectName("subtest")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(120, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(250, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(250, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(120, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(120, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(120, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(250, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(250, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(250, 220, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(250, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(120, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(120, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(120, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(250, 250, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(250, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(120, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(250, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(330, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(330, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(330, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(330, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(330, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_28.setGeometry(QtCore.QRect(330, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(330, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_30.setGeometry(QtCore.QRect(330, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(330, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setGeometry(QtCore.QRect(120, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(250, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_33.setGeometry(QtCore.QRect(330, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setGeometry(QtCore.QRect(120, 310, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(250, 310, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(330, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setGeometry(QtCore.QRect(120, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(250, 340, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_37.setGeometry(QtCore.QRect(330, 340, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setGeometry(QtCore.QRect(120, 370, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_38.setGeometry(QtCore.QRect(250, 370, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_39.setGeometry(QtCore.QRect(330, 370, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setGeometry(QtCore.QRect(430, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setGeometry(QtCore.QRect(430, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setGeometry(QtCore.QRect(430, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setGeometry(QtCore.QRect(430, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setGeometry(QtCore.QRect(430, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(430, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(430, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(430, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(430, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(430, 310, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(430, 340, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_2)
        self.label_56.setGeometry(QtCore.QRect(430, 370, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.subtest.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.subtest.addTab(self.tab_3, "")
        self.tab.addTab(self.test, "")
        self.tab.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.subtest.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">Jane Doe</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Patient ID: jdoe102</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Date Created: 07/18/19</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Last Updated: 05/05/20</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7pt;\"><br /></p></body></html>"))
        self.PaInfo.setAccessibleName(_translate("MainWindow", "asfa"))
        self.lineEdit_2.setText(_translate("MainWindow", "21"))
        self.label.setText(_translate("MainWindow", "Age:"))
        self.label_2.setText(_translate("MainWindow", "Sex:"))
        self.label_3.setText(_translate("MainWindow", "Date of Birth:"))
        self.label_4.setText(_translate("MainWindow", "Weight:"))
        self.lineEdit_3.setText(_translate("MainWindow", "155"))
        self.label_5.setText(_translate("MainWindow", "lbs"))
        self.label_6.setText(_translate("MainWindow", "Height:"))
        self.lineEdit_4.setText(_translate("MainWindow", "5\'11"))
        self.label_7.setText(_translate("MainWindow", "Street Address:"))
        self.lineEdit_5.setText(_translate("MainWindow", "200 Bloomfield Ave"))
        self.label_8.setText(_translate("MainWindow", "City/Town:"))
        self.lineEdit_6.setText(_translate("MainWindow", "West Hartford"))
        self.label_9.setText(_translate("MainWindow", "State:"))
        self.lineEdit_7.setText(_translate("MainWindow", "CT"))
        self.label_10.setText(_translate("MainWindow", "Country:"))
        self.lineEdit_8.setText(_translate("MainWindow", "United State"))
        self.lineEdit_9.setText(_translate("MainWindow", "971-773-1055"))
        self.label_11.setText(_translate("MainWindow", "Primary Contact:"))
        self.lineEdit_10.setText(_translate("MainWindow", "959-965-2323"))
        self.label_12.setText(_translate("MainWindow", "Secondary Contact:"))
        self.lineEdit_11.setText(_translate("MainWindow", "CIGNA"))
        self.lineEdit_12.setText(_translate("MainWindow", "H9564123"))
        self.label_13.setText(_translate("MainWindow", "Insurance:"))
        self.label_14.setText(_translate("MainWindow", "Member ID:"))
        self.label_15.setText(_translate("MainWindow", "Name"))
        self.lineEdit_13.setText(_translate("MainWindow", "959-556-2223"))
        self.label_16.setText(_translate("MainWindow", "Relation:"))
        self.lineEdit_14.setText(_translate("MainWindow", "John Doe"))
        self.label_17.setText(_translate("MainWindow", "Primary Contact:"))
        self.lineEdit_15.setText(_translate("MainWindow", "Brother"))
        self.label_18.setText(_translate("MainWindow", "Emergency Contact:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "F"))
        self.comboBox.setItemText(1, _translate("MainWindow", "M"))
        self.lineEdit_40.setText(_translate("MainWindow", "06117"))
        self.label_57.setText(_translate("MainWindow", "Zip"))
        self.tab.setTabText(self.tab.indexOf(self.PaInfo), _translate("MainWindow", "Patient Information"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Stomach Ulcer \n"
"Chronic head pain\n"
""))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Seafood"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Stool Test\n"
"Blood Test\n"
"Rectal Examination\n"
""))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Tape Worm\n"
"\n"
""))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Cough\n"
"Fever\n"
"Infection \n"
""))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "Avid\n"
"Anti-biotics\n"
""))
        self.label_19.setText(_translate("MainWindow", "Chief Complaint:"))
        self.plainTextEdit_10.setPlainText(_translate("MainWindow", "Stomach Pain\n"
"Loss of Weight\n"
"Dizzy\n"
"Light Headed\n"
"\n"
"\n"
""))
        self.label_20.setText(_translate("MainWindow", "Medical History"))
        self.label_21.setText(_translate("MainWindow", "Allergies"))
        self.label_22.setText(_translate("MainWindow", "Request Tested:"))
        self.label_23.setText(_translate("MainWindow", "Diagnosis:"))
        self.label_24.setText(_translate("MainWindow", "Symptoms:"))
        self.label_25.setText(_translate("MainWindow", "Medication:"))
        self.tab.setTabText(self.tab.indexOf(self.MeInfo), _translate("MainWindow", "Medical Information"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Patient prefer to have a female doctor & a specialist\n"
""))
        self.label_26.setText(_translate("MainWindow", "Visit Notes:"))
        self.tab.setTabText(self.tab.indexOf(self.ViNot), _translate("MainWindow", "Visit Notes"))
        self.plainTextEdit_13.setPlainText(_translate("MainWindow", "2 Weeks "))
        self.pushButton.setText(_translate("MainWindow", "Print"))
        self.label_27.setText(_translate("MainWindow", "Medication Advised"))
        self.plainTextEdit_11.setPlainText(_translate("MainWindow", "Cephalexin, Acetaminophen (Tylenol)"))
        self.label_29.setText(_translate("MainWindow", "Date "))
        self.plainTextEdit_12.setPlainText(_translate("MainWindow", "2 times daily- after food"))
        self.label_30.setText(_translate("MainWindow", "Duration"))
        self.label_28.setText(_translate("MainWindow", "Dose Advised"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Oral medication "))
        self.label_58.setText(_translate("MainWindow", "Type:"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Testing for White Blood Count for patient</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_59.setText(_translate("MainWindow", "Notes:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Intramuscular injection (IM)"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Intravascular injection (IV)"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Subcutaneous injection (SC)"))
        self.label_60.setText(_translate("MainWindow", "Date Taken:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Injection"))
        self.tab.setTabText(self.tab.indexOf(self.pres), _translate("MainWindow", "Prescriptions"))
        self.label_31.setText(_translate("MainWindow", "Hemoglobin"))
        self.lineEdit_16.setText(_translate("MainWindow", "0.60"))
        self.lineEdit_17.setText(_translate("MainWindow", "15.5"))
        self.label_32.setText(_translate("MainWindow", "Potassium"))
        self.label_33.setText(_translate("MainWindow", "Creatinine"))
        self.label_34.setText(_translate("MainWindow", "WBCs"))
        self.lineEdit_18.setText(_translate("MainWindow", "2.5"))
        self.lineEdit_19.setText(_translate("MainWindow", "12.210"))
        self.lineEdit_20.setText(_translate("MainWindow", "155.4"))
        self.lineEdit_21.setText(_translate("MainWindow", "160"))
        self.label_35.setText(_translate("MainWindow", "Fasting Glucose"))
        self.label_36.setText(_translate("MainWindow", "Plasma ACTH"))
        self.label_37.setText(_translate("MainWindow", "Plasma cortisol"))
        self.lineEdit_22.setText(_translate("MainWindow", "398"))
        self.lineEdit_23.setText(_translate("MainWindow", "0.73"))
        self.label_38.setText(_translate("MainWindow", "Total Bilirubin"))
        self.label_39.setText(_translate("MainWindow", "Results:"))
        self.label_40.setText(_translate("MainWindow", "Reference range:"))
        self.lineEdit_24.setText(_translate("MainWindow", "3.5-5.1"))
        self.lineEdit_25.setText(_translate("MainWindow", "<1.2"))
        self.lineEdit_26.setText(_translate("MainWindow", "4.00-10.00"))
        self.lineEdit_27.setText(_translate("MainWindow", "7.2-63.3"))
        self.lineEdit_28.setText(_translate("MainWindow", "62-180"))
        self.lineEdit_29.setText(_translate("MainWindow", "0.70-1.2"))
        self.lineEdit_30.setText(_translate("MainWindow", "60-100"))
        self.lineEdit_31.setText(_translate("MainWindow", "13.5-17.0"))
        self.label_41.setText(_translate("MainWindow", "Testosterone"))
        self.lineEdit_32.setText(_translate("MainWindow", "2.57"))
        self.lineEdit_33.setText(_translate("MainWindow", "4.6-31"))
        self.label_42.setText(_translate("MainWindow", "Phosphate"))
        self.lineEdit_34.setText(_translate("MainWindow", "2.6"))
        self.lineEdit_35.setText(_translate("MainWindow", "2.7-4.5"))
        self.label_43.setText(_translate("MainWindow", "Calcium"))
        self.lineEdit_36.setText(_translate("MainWindow", "8.8"))
        self.lineEdit_37.setText(_translate("MainWindow", "8.6-10.2"))
        self.label_44.setText(_translate("MainWindow", "Calcitonin"))
        self.lineEdit_38.setText(_translate("MainWindow", "272"))
        self.lineEdit_39.setText(_translate("MainWindow", "<20"))
        self.label_45.setText(_translate("MainWindow", "10^9/L"))
        self.label_46.setText(_translate("MainWindow", "g/dL"))
        self.label_47.setText(_translate("MainWindow", "mMol/L"))
        self.label_48.setText(_translate("MainWindow", "mg/dL"))
        self.label_49.setText(_translate("MainWindow", "mg/dL"))
        self.label_50.setText(_translate("MainWindow", "mg/dL"))
        self.label_51.setText(_translate("MainWindow", "ng/L"))
        self.label_52.setText(_translate("MainWindow", "ug/L"))
        self.label_53.setText(_translate("MainWindow", "nmoli/L"))
        self.label_54.setText(_translate("MainWindow", "mg/dL"))
        self.label_55.setText(_translate("MainWindow", "mg/dL"))
        self.label_56.setText(_translate("MainWindow", "<20ng/L"))
        self.subtest.setTabText(self.subtest.indexOf(self.tab_2), _translate("MainWindow", "Blood Test"))
        self.subtest.setTabText(self.subtest.indexOf(self.tab_3), _translate("MainWindow", "Tab 2"))
        self.tab.setTabText(self.tab.indexOf(self.test), _translate("MainWindow", "Test Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

